sfdx-source/packaged/main/trigger-utils/objects/HandlerControl__mdt/HandlerControl__mdt.object-meta.xml
<CustomObject>
    <description>Registers a trigger handler that implements the interface with the framework and allows to control execution.</description>
    <label>Handler Control</label>
    <pluralLabel>Handler Controls</pluralLabel>
</CustomObject>

sfdx-source/packaged/main/trigger-utils/objects/HandlerControl__mdt/fields/Handler__c.field-meta.xml
<CustomField>
    <fullName>Handler__c</fullName>
    <description>The exact class name of the handler that implements the interface. This is used to dynamically construct the class during runtime.</description>
    <inlineHelpText>The developer name of the Apex Class that implements the interface</inlineHelpText>
    <label>Handler</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

src/packaged/main/trigger-utils/objects/HandlerControl__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Activates the handler to be processed during execution of triggers.</description>
    <inlineHelpText>Activates the handler for processing</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/packaged/main/trigger-utils/objects/HandlerControl__mdt/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The order of execution for this specific handler. Higher numbers are executed earlier in a transaction.</description>
    <inlineHelpText>Higher priorities are executed earlier during a transaction.</inlineHelpText>
    <label>Priority</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/packaged/main/trigger-utils/objects/HandlerControl__mdt/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <description>The SObject for which the configuration will be executed.</description>
    <inlineHelpText>Select the SObject-Type where this configuration will be triggered</inlineHelpText>
    <label>SObject</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Triggers</relationshipLabel>
    <relationshipName>Triggers</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

src/packaged/main/trigger-utils/classes/Dispatcher.cls
public class Dispatcher {

    /** @Description    All handlers that will be executed in this transaction */
    @testVisible List<ITriggerHandler> activeHandlers;

    /** @Description
    *   Initializes the dispatcher without scope
    */
    public Dispatcher() {
        activeHandlers = new List<ITriggerHandler>();
    }

    /** @Description
    *   Initializes the dispatcher with the scope of the a SObject type and loads all handlers for this config
    *
    *   @param  sObjToken   Token for the SObject to be executed
    */
    public Dispatcher(Schema.SObjectType SObjToken) {
        activeHandlers = initHandlers([SELECT DeveloperName,Handler__c,Priority__c,SObject__c
                                       FROM HandlerControl__mdt
                                       WHERE SObject__r.QualifiedApiName = :SObjToken.getDescribe().getName() AND IsActive__c = true ORDER BY Priority__c DESC]);
    }

    /**
    *   @Description
    *   This method is called with a list of registered handler configs and tries to construct
    *   the triggerhandler implementations with dynamic type casting on run time and stores them in a cache
    *   If the initialization fails, the handler is skipped (but all other handlers still succeed)
    *
    *   @param  handlerControls     All handlers that are about to be executed
    *
    *   @return                     Ordered list of handlers (by priority) for this scope
    */
    public List<ITriggerHandler> initHandlers(List<HandlerControl__mdt> handlerControls) {
        List<ITriggerHandler> handlers = new List<ITriggerHandler>();
        for (HandlerControl__mdt hc : handlerControls) {
            try {
                ITriggerHandler triggerHandler = (ITriggerHandler)Type.forName(hc.Handler__c).newInstance(); 
                if (triggerHandler != null) handlers.add(triggerHandler);
            }
            catch (Exception e) { 
                System.debug(LoggingLevel.ERROR, 'Typecast failed for: ' + hc);
                System.debug(LoggingLevel.ERROR, 'Exception Type Name: ' + e.getTypeName());  
                System.debug(LoggingLevel.ERROR, 'Exception Message: ' + e.getMessage());
            }
        }
        return handlers;
    }

    /** @Description
    *   Executes all handlers in the prioritized order (higher priority is executed first)
    */
    public void executeHandlers() {
        for (ITriggerHandler handler : activeHandlers) handler.execute();
    }

}