sfdx-source/packaged/main/core/objects/AccessToken__c/AccessToken__c.object-meta.xml
<CustomObject>
    <description>Issued access token for Contacts that allows to access the time entry approval page.</description>
    <label>Access Token</label>
    <nameField>
        <displayFormat>TOK-{0000000}</displayFormat>
        <label>Token Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Tokens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/packaged/main/default/objects/AccessToken__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description>The unique access code that is auto-generated for the contact.</description>
    <inlineHelpText>The auto-generated access code for the contact.</inlineHelpText>
    <label>Code</label>
    <length>12</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/packaged/main/default/objects/AccessToken__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/packaged/time-tracking/classes/TimeEntryApprovalController.cls
public with sharing class TimeEntryApprovalController {
    
    /**
    *   @description
    *   Queries the database for a valid access code and returns true, if it found
    *   an access code AND the access code is valid.
    *
    *   @param  accessCode          The 12-character string
    *
    *   @return                     True, if the entered access code is valid
    */
    @AuraEnabled
    public static Boolean validateAccessCode(String accessCode) {
        List<AccessToken__c> ats = [SELECT Id,Status__c FROM AccessToken__c WHERE Status__c = 'Active' AND Code__c = :String.escapeSingleQuotes(accessCode)];
        if (ats.isEmpty()) return false;
        return ats[0].Status__c == 'Active';
    }
}