sfdx-source/packaged/main/core/objects/AccessToken__c/AccessToken__c.object-meta.xml
<CustomObject>
    <description>Issued access token for Contacts that allows to access the time entry approval page.</description>
    <label>Access Token</label>
    <nameField>
        <displayFormat>TOK-{0000000}</displayFormat>
        <label>Token Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Access Tokens</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/packaged/main/default/objects/AccessToken__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description>The unique access code that is auto-generated for the contact.</description>
    <inlineHelpText>The auto-generated access code for the contact.</inlineHelpText>
    <label>Code</label>
    <length>12</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

sfdx-source/packaged/main/core/objects/AccessToken__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>AccessTokens</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/packaged/main/default/objects/AccessToken__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/packaged/time-tracking/classes/TimeEntryApprovalController_Test.cls
@isTest
class TimeEntryApprovalController_Test {

    @TestSetup
    static void makeData(){

        Account a = TestDataFactory.CreateDefaultAccount();
        insert a;

        Contact c = TestDataFactory.CreateContact(new Contact(AccountId = a.Id));
        insert c;

        List<AccessToken__c> ats = new List<AccessToken__c>();
        ats.add(TestDataFactory.CreateAccessToken(new AccessToken__c(Contact__c=c.Id, Code__c='ABCD1234XYZ1', Status__c='Active')));
        ats.add(TestDataFactory.CreateAccessToken(new AccessToken__c(Contact__c=c.Id, Code__c='ABCD1234XYZ2', Status__c='Active')));
        ats.add(TestDataFactory.CreateAccessToken(new AccessToken__c(Contact__c=c.Id, Code__c='ABCD1234XYZ3', Status__c='Revoked')));
        insert ats;
    }
    
    @isTest
    static void validateAccessCode_ValidCode_True() {
        // ACTION
        Boolean isValid = TimeEntryApprovalController.validateAccessCode('ABCD1234XYZ1');
        // VERIFY
        System.assertEquals(true, isValid, 'validateAccessCode(ABCD1234XYZ1)');
    }

    @isTest
    static void validateAccessCode_NonExistingCode_False() {
        // ACTION
        Boolean isValid = TimeEntryApprovalController.validateAccessCode('ABCD');
        // VERIFY
        System.assertEquals(false, isValid, 'validateAccessCode(ABCD)');
    }

    @isTest
    static void validateAccessCode_RevokedCode_False() {
        // ACTION
        Boolean isValid = TimeEntryApprovalController.validateAccessCode('ABCD1234XYZ3');
        // VERIFY
        System.assertEquals(false, isValid, 'validateAccessCode(ABCD1234XYZ3)');
    }

}