sfdx-source/packaged/main/core/objects/CompanyData__mdt/CompanyData__mdt.object-meta.xml
<CustomObject>
    <description>Stores Contact Information for the Organization. Compensates for the lack of creating custom fields on Organization Object. Used in Visualforce to display company info in header / footer</description>
    <label>Company Data</label>
    <pluralLabel>Company Data</pluralLabel>
</CustomObject>

sfdx-source/packaged/main/core/objects/CompanyData__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Generic value field that can store any string</description>
    <inlineHelpText>Enter the value for this info</inlineHelpText>
    <label>Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/packaged/invoice-pdf-generation/classes/OrganizationInfo.cls
/** @Description
*   Singleton pattern to expose company data from custom metadata
*/
public class OrganizationInfo {

    public String Email {public get; private set;}
    public String Phone {public get; private set;}
    public String Name {public get; private set;}
    public String VATNumber {public get; private set;}

    public String Street {public get; private set;}
    public String PostalCode {public get; private set;}
    public String City {public get; private set;}
    public String Country {public get; private set;}

    public OrganizationInfo() {

        Map<String, String> data = new Map<String, String>();
        for (CompanyData__mdt cd : [SELECT DeveloperName,Label,Value__c FROM CompanyData__mdt]) data.put(cd.DeveloperName, cd.Value__c);
        
        Name = data.get('NAME');
        Phone = data.get('PHONE');
        Email = data.get('EMAIL');
        Street = data.get('STREET');
        PostalCode = data.get('POSTAL_CODE');
        City = data.get('CITY');
        Country = data.get('COUNTRY');
        VATNumber = data.get('VAT_NUMBER');
    }

}