sfdx-source/packaged/main/core/objects/InvoiceLineItem__c/InvoiceLineItem__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>OLI Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/packaged/main/default/objects/InvoiceLineItem__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Short description of the invoice line item</description>
    <inlineHelpText>Enter short description of line item</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

sfdx-source/packaged/main/core/objects/InvoiceLineItem__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/packaged/main/default/objects/InvoiceLineItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>InvoiceLineItems</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/packaged/main/core/objects/InvoiceLineItem__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

src/packaged/main/default/objects/InvoiceLineItem__c/fields/ServiceDate__c.field-meta.xml
<CustomField>
    <fullName>ServiceDate__c</fullName>
    <description>Retrieved from Time Entry date</description>
    <inlineHelpText>Service Date of the line item, retrieved from Time Entry</inlineHelpText>
    <label>Service Date</label>
    <type>Date</type>
</CustomField>

sfdx-source/packaged/main/core/objects/TimeEntry__c/TimeEntry__c.object-meta.xml
<CustomObject>
    <description>An individual time entry as unit of work that can be invoiced.</description>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>{YYYYMMDD}-{000000}</displayFormat>
        <label>Time Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/packaged/main/core/objects/TimeEntry__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>The calender date where this time entry / work occured</description>
    <inlineHelpText>Calender date where work was done</inlineHelpText>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

sfdx-source/packaged/main/core/objects/TimeEntry__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Short description of the performed work</description>
    <inlineHelpText>Enter short description of the work performed</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

sfdx-source/packaged/main/core/objects/TimeEntry__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>Calculated duration in decimal hour format (3 hours 30 minutes = 3,5)</description>
    <formula>(HOUR(EndTime__c) - HOUR(StartTime__c)) + (MINUTE(EndTime__c)-MINUTE(StartTime__c)) / 60</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Calculated duration</inlineHelpText>
    <label>Duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

sfdx-source/packaged/main/core/objects/TimeEntry__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>TimeEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/packaged/main/core/objects/TimeEntry__c/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <formula>DailyRate__c * (Duration__c / 8)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

sfdx-source/packaged/main/core/classes/TimeEntry.cls
/** @Description
*   This is the decorator object for the custom object InvoiceLineItem__c.
*/
public class TimeEntry {

    /** @Description    The decorated original SObject */
    public TimeEntry__c Record {public get; private set;}

    /** @Description    Create Decorator from original SObject record */
    public TimeEntry(TimeEntry__c originalRecord) {
        Record = originalRecord;
    }

    /** @Description
    *   Create an invoice line item decorator from this time entry that can be added
    *   to an existing invoice
    *
    *   @return                 Invoice line item that has been created from internal record
    */
    public InvoiceLineItem getInvoiceLineItem() {
        InvoiceLineItem__c lineItemRecord = new InvoiceLineItem__c(Price__c = Record.TotalAmount__c,
                                                                   Quantity__c = Record.Duration__c / 8,
                                                                   Description__c = Record.Description__c,
                                                                   ServiceDate__c = Record.Date__c,
                                                                   Product__c = Record.Product__c);
        return new InvoiceLineItem(lineItemRecord);
    }
}