sfdx-source/packaged/main/core/objects/BankAccount__c/BankAccount__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/packaged/main/core/objects/BankAccount__c/fields/BankAccountOwner__c.field-meta.xml
<CustomField>
    <fullName>BankAccountOwner__c</fullName>
    <description>Official Owner of the Bank Account</description>
    <inlineHelpText>Enter Owner of Bank Account</inlineHelpText>
    <label>Bank Account Owner</label>
    <required>true</required>
    <type>Text</type>
    <length>100</length>
</CustomField>

sfdx-source/packaged/main/core/objects/BankAccount__c/fields/BankName__c.field-meta.xml
<CustomField>
    <fullName>BankName__c</fullName>
    <description>Readable name of the bank. Will be printed on Invoice.</description>
    <inlineHelpText>Enter the displayed name of the bank.</inlineHelpText>
    <label>Bank Name</label>
    <required>true</required>
    <type>Text</type>
    <length>50</length>
</CustomField>

sfdx-source/packaged/main/core/objects/BankAccount__c/fields/BankNameFull__c.field-meta.xml
<CustomField>
    <fullName>BankNameFull__c</fullName>
    <description>Full legal name of the bank. Use this if printable name is too long.</description>
    <inlineHelpText>Enter full legal name of the bank</inlineHelpText>
    <label>Bank Name</label>
    <type>Text</type>
    <length>255</length>
</CustomField>

src/packaged/main/default/objects/BankAccount__c/fields/IBAN__c.field-meta.xml
<CustomField>
    <fullName>IBAN__c</fullName>
    <description>International Bank Account Number</description>
    <inlineHelpText>Enter IBAN with Country Code without spaces and formatting.</inlineHelpText>
    <label>IBAN</label>
    <required>true</required>
    <type>Text</type>
    <length>34</length>
</CustomField>

sfdx-source/packaged/main/core/objects/BankAccount__c/fields/IsDefault__c.field-meta.xml
<CustomField>
    <fullName>IsDefault__c</fullName>
    <description>Activates this bank account as default. The default bank account will be used when creating invoices.</description>
    <inlineHelpText>Activate to use this as your default bank account for all invoices.</inlineHelpText>
    <label>Is Default</label>
    <type>Checkbox</type>
    <defaultValue>false</defaultValue>
</CustomField>

sfdx-source/packaged/main/core/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/packaged/main/core/objects/Invoice__c/fields/OrganizationProfile__c.field-meta.xml
<CustomField>
    <fullName>OrganizationProfile__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The organization profile that is used to render the PDF and where the Invoice is billed for</description>
    <label>Organization Profile</label>
    <referenceTo>OrganizationProfile__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/packaged/main/core/objects/OrganizationProfile__c/OrganizationProfile__c.object-meta.xml
<CustomObject>
    <description>Configure and manage organization profiles. Profiles are used when generating invoice PDFs to populate the sender information.</description>
    <label>Organization Profile</label>
    <nameField>
        <label>Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organization Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/packaged/main/core/objects/OrganizationProfile__c/fields/BankAccount__c.field-meta.xml
<CustomField>
    <fullName>BankAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Bank Account details for this organization profile, used for invoice PDF generation.</description>
    <label>Bank Account</label>
    <referenceTo>BankAccount__c</referenceTo>
    <relationshipLabel>Organization Profiles</relationshipLabel>
    <relationshipName>OrganizationProfiles</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/packaged/main/core/objects/OrganizationProfile__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Address City for this organization profile that will be displayed on generated PDFs</description>
    <label>City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfdx-source/packaged/main/core/objects/OrganizationProfile__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Address Country for this organization profile that will be displayed on generated PDFs</description>
    <label>Country</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfdx-source/packaged/main/core/objects/OrganizationProfile__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Primary contact email for this organization profile that will be displayed on generated PDFs</description>
    <label>Email</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfdx-source/packaged/main/core/objects/OrganizationProfile__c/fields/IsDefault__c.field-meta.xml
<CustomField>
    <fullName>IsDefault__c</fullName>
    <description>Activates this profile to use as default, if the user does not have a specific profile configured.</description>
    <inlineHelpText>Use this profile as default for all users</inlineHelpText>
    <label>Is Default</label>
    <type>Checkbox</type>
    <defaultValue>true</defaultValue>
</CustomField>

src/packaged/main/default/objects/OrganizationProfile__c/fields/OrganizationName__c.field-meta.xml
<CustomField>
    <fullName>OrganizationName__c</fullName>
    <description>The organization's name that will be used in headers and footers of generated PDFs</description>
    <inlineHelpText>Your company's name</inlineHelpText>
    <label>Organization Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/packaged/main/default/objects/OrganizationProfile__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <description>Primary contact phone for this organization profile that will be displayed on generated PDFs</description>
    <label>Phone</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/packaged/main/default/objects/OrganizationProfile__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <description>Address Postal Code for this organization profile that will be displayed on generated PDFs</description>
    <label>Postal Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

src/packaged/main/default/objects/OrganizationProfile__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>Address State for this organization profile that will be displayed on generated PDFs</description>
    <label>State</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/packaged/main/default/objects/OrganizationProfile__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <description>Address Street for this organization profile that will be displayed on generated PDFs</description>
    <label>Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/packaged/main/core/objects/OrganizationProfile__c/fields/VATNumber__c.field-meta.xml
<CustomField>
    <fullName>VATNumber__c</fullName>
    <description>VAT Number for this organization profile that will be displayed on generated PDFs</description>
    <inlineHelpText>VAT Number with Country Code (i.e. DE)</inlineHelpText>
    <label>VAT Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

sfdx-source/packaged/invoice-pdf-generation/classes/InvoiceTriggerPdfGeneration.cls
public class InvoiceTriggerPdfGeneration implements Queueable {

    private List<InvoicePrint> Invoices = new List<InvoicePrint>();

    public InvoiceTriggerPdfGeneration(Set<Id> invoiceIds) {
        for (Invoice__c inv : Database.query(Invoice.QUERY_STRING + ' WHERE Id IN :invoiceIds')) {
            Invoices.add(new InvoicePrint(inv));
        }
    }
    
    public void execute(QueueableContext context) {
        
        Map<Id, OrganizationProfile__c> orgProfiles = new Map<Id, OrganizationProfile__c>(
            [SELECT Id,Name,OrganizationName__c,Street__c,PostalCode__c,City__c,State__c,Country__c,Email__c,Phone__c,VATNumber__c,IsDefault__c,
                    BankAccount__r.IBAN__c,BankAccount__r.BankName__c,BankAccount__r.BankNameFull__c,BankAccount__r.BankAccountOwner__c
            FROM OrganizationProfile__c]
        );

        for (InvoicePrint ip : Invoices) {
            PageReference invoicePdfPage = Page.InvoicePdf;
            // invoicePdfPage.OrgProfile = orgProfiles.get(ip.Record.OrganizationProfile__c);
        }
    }

}