sfdx-source/packaged/main/core/objects/BankAccount__c/BankAccount__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/packaged/main/core/objects/BankAccount__c/fields/BankAccountOwner__c.field-meta.xml
<CustomField>
    <fullName>BankAccountOwner__c</fullName>
    <description>Official Owner of the Bank Account</description>
    <inlineHelpText>Enter Owner of Bank Account</inlineHelpText>
    <label>Bank Account Owner</label>
    <required>true</required>
    <type>Text</type>
    <length>100</length>
</CustomField>

sfdx-source/packaged/main/core/objects/BankAccount__c/fields/BankName__c.field-meta.xml
<CustomField>
    <fullName>BankName__c</fullName>
    <description>Readable name of the bank. Will be printed on Invoice.</description>
    <inlineHelpText>Enter the displayed name of the bank.</inlineHelpText>
    <label>Bank Name</label>
    <required>true</required>
    <type>Text</type>
    <length>50</length>
</CustomField>

src/packaged/main/default/objects/BankAccount__c/fields/IBAN__c.field-meta.xml
<CustomField>
    <fullName>IBAN__c</fullName>
    <description>International Bank Account Number</description>
    <inlineHelpText>Enter IBAN with Country Code without spaces and formatting.</inlineHelpText>
    <label>IBAN</label>
    <required>true</required>
    <type>Text</type>
    <length>34</length>
</CustomField>

sfdx-source/packaged/main/core/objects/BankAccount__c/fields/IsDefault__c.field-meta.xml
<CustomField>
    <fullName>IsDefault__c</fullName>
    <description>Activates this bank account as default. The default bank account will be used when creating invoices.</description>
    <inlineHelpText>Activate to use this as your default bank account for all invoices.</inlineHelpText>
    <label>Is Default</label>
    <type>Checkbox</type>
    <defaultValue>false</defaultValue>
</CustomField>

sfdx-source/packaged/invoice-pdf-generation/classes/VFInvoicePdfController.cls
public with sharing class VFInvoicePdfController {
    
    /** @Description    The fully initialized invoice object for this context */
    public InvoicePrint Invoice {
        public get {
            if (Invoice == null) {
                Invoice = new InvoicePrint(ApexPages.currentPage().getParameters().get('Id'));
            }
            return Invoice;
        }
        private set;
    }

    /** @Description    The fully initialized org data for this context */
    public OrganizationInfo Company {
        public get {
            if (Company == null) {
                Company = new OrganizationInfo();
            }
            return Company;
        }
        private set;
    }

    /** @Description    Render As Property from Page Parameters */
    public String renderAs {
        public get {
            renderAs = ApexPages.currentPage().getParameters().get('renderAs');
            return renderAs;
        }
        public set;
    }

    /** @Description    Get default bank account */
    public BankAccount__c BankAccount {
        public get {
            if (BankAccount == null) {
                List<BankAccount__c> baccs = [SELECT Id,BankName__c,IBAN__c,BankAccountOwner__c FROM BankAccount__c WHERE IsDefault__c = true];
                BankAccount = baccs.isEmpty() ? new BankAccount__c() : baccs[0];
            }
            return BankAccount;
        }
        public set;
    }

    /** @Description    Language Property from Page Parameters */
    public String Language {
        public get {
            Language = Invoice.Record.PdfLanguage__c;
            return Language;
        }
        public set;
    }

}