sfdx-source/packaged/main/core/objects/BankAccount__c/BankAccount__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/packaged/main/core/objects/BankAccount__c/fields/BankAccountOwner__c.field-meta.xml
<CustomField>
    <fullName>BankAccountOwner__c</fullName>
    <description>Official Owner of the Bank Account</description>
    <inlineHelpText>Enter Owner of Bank Account</inlineHelpText>
    <label>Bank Account Owner</label>
    <required>true</required>
    <type>Text</type>
    <length>100</length>
</CustomField>

sfdx-source/packaged/main/core/objects/BankAccount__c/fields/BankName__c.field-meta.xml
<CustomField>
    <fullName>BankName__c</fullName>
    <description>Readable name of the bank. Will be printed on Invoice.</description>
    <inlineHelpText>Enter the displayed name of the bank.</inlineHelpText>
    <label>Bank Name</label>
    <required>true</required>
    <type>Text</type>
    <length>50</length>
</CustomField>

src/packaged/main/default/objects/BankAccount__c/fields/IBAN__c.field-meta.xml
<CustomField>
    <fullName>IBAN__c</fullName>
    <description>International Bank Account Number</description>
    <inlineHelpText>Enter IBAN with Country Code without spaces and formatting.</inlineHelpText>
    <label>IBAN</label>
    <required>true</required>
    <type>Text</type>
    <length>34</length>
</CustomField>

sfdx-source/packaged/main/core/objects/BankAccount__c/fields/IsDefault__c.field-meta.xml
<CustomField>
    <fullName>IsDefault__c</fullName>
    <description>Activates this bank account as default. The default bank account will be used when creating invoices.</description>
    <inlineHelpText>Activate to use this as your default bank account for all invoices.</inlineHelpText>
    <label>Is Default</label>
    <type>Checkbox</type>
    <defaultValue>false</defaultValue>
</CustomField>

sfdx-source/packaged/main/core/objects/CompanyData__mdt/CompanyData__mdt.object-meta.xml
<CustomObject>
    <description>Stores Contact Information for the Organization. Compensates for the lack of creating custom fields on Organization Object. Used in Visualforce to display company info in header / footer</description>
    <label>Company Data</label>
    <pluralLabel>Company Data</pluralLabel>
</CustomObject>

sfdx-source/packaged/main/core/objects/CompanyData__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Generic value field that can store any string</description>
    <inlineHelpText>Enter the value for this info</inlineHelpText>
    <label>Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdx-source/packaged/main/core/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/packaged/main/core/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>The Billing Account for this Invoice. Information from this Account are printed on the Invoice.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

sfdx-source/packaged/main/core/objects/Invoice__c/fields/PdfLanguage__c.field-meta.xml
<CustomField>
    <fullName>PdfLanguage__c</fullName>
    <label>Language (PDF)</label>
    <inlineHelpText>Set the languge of the rendered PDF</inlineHelpText>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <label>German (Germany)</label>
                <default>true</default>
                <fullName>de_DE</fullName>
            </value>
            <value>
                <label>English (Germany)</label>
                <fullName>en_DE</fullName>
            </value>
            <value>
                <label>English (USA)</label>
                <fullName>en_US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/packaged/invoice-pdf-generation/classes/VFInvoicePdfController_Test.cls
@isTest
public class VFInvoicePdfController_Test {

    @TestSetup
    static void makeData(){
        Account a = TestDataFactory.CreateDefaultAccount();
        insert a;
        Invoice__c defaultInvoice = TestDataFactory.CreateInvoice(new Invoice__c(Account__c = a.Id));
        insert defaultInvoice;
    }
    
    @isTest
    static void getInvoice_NullId_EmptyInvoice() {
        // SETUP
        Test.setCurrentPage(Page.InvoicePdf);
        // VERIFY
        System.assertNotEquals(null, new VFInvoicePdfController().Invoice, 'Invoice');
        System.assertEquals(new Invoice__c(), new VFInvoicePdfController().Invoice.Record, 'Invoice.Record');
    }

    @isTest
    static void getInvoice_EmptyId_EmptyInvoice() {
        // SETUP
        Test.setCurrentPage(Page.InvoicePdf);
        ApexPages.currentPage().getParameters().put('Id', '');
        // VERIFY
        System.assertNotEquals(null, new VFInvoicePdfController().Invoice, 'Invoice');
        System.assertEquals(new Invoice__c(), new VFInvoicePdfController().Invoice.Record, 'Invoice.Record');
    }

    @isTest
    static void getInvoice_ValidId_EmptyInvoice() {
        // SETUP
        Invoice__c record = [SELECT Id FROM Invoice__c LIMIT 1];
        Test.setCurrentPage(Page.InvoicePdf);
        ApexPages.currentPage().getParameters().put('Id', record.Id);

        // VERIFY
        System.assertEquals(record.Id, new VFInvoicePdfController().Invoice.Record.Id, 'Invoice.Record.Id');
    }

    @isTest
    static void getCompany_MetadataDataWrapped() {
        // ACTION
        OrganizationInfo oInfo = new VFInvoicePdfController().Company;
        // VERIFY
        System.assertEquals([SELECT Value__c FROM CompanyData__mdt WHERE DeveloperName = 'NAME'].Value__c, oInfo.Name, 'Name');
        System.assertEquals([SELECT Value__c FROM CompanyData__mdt WHERE DeveloperName = 'PHONE'].Value__c, oInfo.Phone, 'Phone');
        System.assertEquals([SELECT Value__c FROM CompanyData__mdt WHERE DeveloperName = 'EMAIL'].Value__c, oInfo.Email, 'Email');
        System.assertEquals([SELECT Value__c FROM CompanyData__mdt WHERE DeveloperName = 'STREET'].Value__c, oInfo.Street, 'Street');
        System.assertEquals([SELECT Value__c FROM CompanyData__mdt WHERE DeveloperName = 'POSTAL_CODE'].Value__c, oInfo.PostalCode, 'PostalCode');
        System.assertEquals([SELECT Value__c FROM CompanyData__mdt WHERE DeveloperName = 'CITY'].Value__c, oInfo.City, 'City');
        System.assertEquals([SELECT Value__c FROM CompanyData__mdt WHERE DeveloperName = 'COUNTRY'].Value__c, oInfo.Country, 'Country');
    }

    @isTest
    static void getRenderAs_ValueFromPageParam() {
        // SETUP
        Test.setCurrentPage(Page.InvoicePdf);
        ApexPages.currentPage().getParameters().put('renderAs', 'pdf');
        // VERIFY
        System.assertEquals('pdf', new VFInvoicePdfController().renderAs, 'renderAs');
    }

    @isTest
    static void getBankAccount_NoBankAccount_EmptyBankAccount() {
        // VERIFY
        System.assertEquals(new BankAccount__c(), new VFInvoicePdfController().BankAccount, 'BankAccount');
    }

    @isTest
    static void getBankAccount_HasDefaultBankAccount_DefaultBankAccount() {
        // SETUP
        BankAccount__c defaultBA = TestDataFactory.CreateBankAccount(new BankAccount__c(IsDefault__c = true));
        BankAccount__c otherBA = TestDataFactory.CreateBankAccount(new BankAccount__c(IsDefault__c = false, IBAN__c = 'DE000000000000000'));
        insert new List<BankAccount__c>{defaultBA, otherBA};
        // VERIFY
        System.assertEquals(defaultBA.Id, new VFInvoicePdfController().BankAccount.Id, 'BankAccount.Id');
        System.assertEquals(defaultBA.BankAccountOwner__c, new VFInvoicePdfController().BankAccount.BankAccountOwner__c, 'BankAccount.BankAccountOwner__c');
        System.assertEquals(defaultBA.BankName__c, new VFInvoicePdfController().BankAccount.BankName__c, 'BankAccount.BankName__c');
        System.assertEquals(defaultBA.IBAN__c, new VFInvoicePdfController().BankAccount.IBAN__c, 'BankAccount.IBAN__c');
    }

    @isTest
    static void getLanguage_ValueFromInvoiceReturned() {
        // SETUP
        Invoice__c record = [SELECT Id,PdfLanguage__c FROM Invoice__c LIMIT 1];
        record.PdfLanguage__c = 'en_DE';
        update record;
        Test.setCurrentPage(Page.InvoicePdf);
        ApexPages.currentPage().getParameters().put('Id', record.Id);
        
        // VERIFY
        System.assertEquals('en_DE', new VFInvoicePdfController().Language, 'Language');
    }
}