sfdx-source/packaged/main/core/objects/BankAccount__c/BankAccount__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/packaged/main/core/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/packaged/main/core/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>The Billing Account for this Invoice. Information from this Account are printed on the Invoice.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

sfdx-source/packaged/main/core/objects/Invoice__c/fields/OrganizationProfile__c.field-meta.xml
<CustomField>
    <fullName>OrganizationProfile__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The organization profile that is used to render the PDF and where the Invoice is billed for</description>
    <label>Organization Profile</label>
    <referenceTo>OrganizationProfile__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/packaged/main/core/objects/OrganizationProfile__c/OrganizationProfile__c.object-meta.xml
<CustomObject>
    <description>Configure and manage organization profiles. Profiles are used when generating invoice PDFs to populate the sender information.</description>
    <label>Organization Profile</label>
    <nameField>
        <label>Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organization Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/packaged/main/core/objects/OrganizationProfile__c/fields/BankAccount__c.field-meta.xml
<CustomField>
    <fullName>BankAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Bank Account details for this organization profile, used for invoice PDF generation.</description>
    <label>Bank Account</label>
    <referenceTo>BankAccount__c</referenceTo>
    <relationshipLabel>Organization Profiles</relationshipLabel>
    <relationshipName>OrganizationProfiles</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/packaged/invoice-pdf-generation/classes/InvoiceTriggerPdfGeneration_Test.cls
@isTest
public class InvoiceTriggerPdfGeneration_Test {

    @TestSetup
    static void makeData(){
        Account a = TestDataFactory.CreateAccount(
            new Account(BillingStreet = 'Teststraße 1', BillingPostalCode = '80336', BillingCity = 'München', BillingCountryCode = 'DE')
        );
        insert a;

        BankAccount__c ba = TestDataFactory.CreateDefaultBankAccount();
        insert ba;

        OrganizationProfile__c op = TestDataFactory.CreateOrganizationProfile(new OrganizationProfile__c(BankAccount__c = ba.Id));
        insert op;
    }
    
    @isTest
    static void enqueue_SingleInvoiceId_NewPdfDocumentRendered() {
        // SETUP
        Account a = [SELECT Id FROM Account LIMIT 1];
        OrganizationProfile__c op = [SELECT Id FROM OrganizationProfile__c LIMIT 1];
        Invoice__c i = TestDataFactory.CreateInvoice(new Invoice__c(Account__c = a.Id, OrganizationProfile__c = op.Id));
        insert i;

        // ACTION
        InvoiceTriggerPdfGeneration job = new InvoiceTriggerPdfGeneration(new Set<Id>{i.Id});
        job.execute(null);

        // VERIFY
        System.assertEquals(1, [SELECT COUNT() FROM ContentDocumentLink WHERE LinkedEntityId = :i.Id], 'COUNT() FROM ContentDocumentLink');
    }

    @isTest
    static void enqueue_BatchInvoiceIds_NewPdfDocumentsRendered() {
        // SETUP
        Account a = [SELECT Id FROM Account LIMIT 1];
        OrganizationProfile__c op = [SELECT Id FROM OrganizationProfile__c LIMIT 1];
        List<Invoice__c> invs = new List<Invoice__c>();
        for (Integer i = 0; i < 10; i++) {
            invs.add(TestDataFactory.CreateInvoice(new Invoice__c(Account__c = a.Id, OrganizationProfile__c = op.Id)));
        }
        insert invs;

        Set<Id> invIds = new Set<Id>();
        for (Invoice__c inv : invs) invIds.add(inv.Id);

        // ACTION
        InvoiceTriggerPdfGeneration job = new InvoiceTriggerPdfGeneration(invIds);
        job.execute(null);

        // VERIFY
        System.assertEquals(invs.size(), [SELECT COUNT() FROM ContentDocumentLink WHERE LinkedEntityId IN :invIds], 'COUNT() FROM ContentDocumentLink');
    }

    @isTest
    static void enqueue_BatchInvoiceIdsWithContentDocuments_NewPdfDocumentVersionsRendered() {
        // SETUP
        Account a = [SELECT Id FROM Account LIMIT 1];
        OrganizationProfile__c op = [SELECT Id FROM OrganizationProfile__c LIMIT 1];
        List<Invoice__c> invs = new List<Invoice__c>();
        for (Integer i = 0; i < 10; i++) {
            invs.add(TestDataFactory.CreateInvoice(new Invoice__c(Account__c = a.Id, OrganizationProfile__c = op.Id)));
        }
        insert invs;

        Set<Id> invIds = new Set<Id>();
        for (Invoice__c inv : invs) invIds.add(inv.Id);

        // ACTION
        InvoiceTriggerPdfGeneration job = new InvoiceTriggerPdfGeneration(invIds);
        job.execute(null);
        job.execute(null);

        // VERIFY
        System.assertEquals(invs.size() * 2, [SELECT COUNT() FROM ContentVersion], 'COUNT() FROM ContentVersion');
    }
    
}