sfdx-source/packaged/main/core/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/packaged/main/core/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>The Billing Account for this Invoice. Information from this Account are printed on the Invoice.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

sfdx-source/packaged/main/core/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/packaged/main/core/objects/InvoiceLineItem__c/InvoiceLineItem__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>OLI Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/packaged/main/core/objects/InvoiceLineItem__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

sfdx-source/packaged/invoicing/classes/InvoiceController_Test.cls
@isTest
public class InvoiceController_Test {

    @TestSetup
    static void makeData(){
        Account a = TestDataFactory.CreateDefaultAccount();
        insert a;

        List<Invoice__c> invoices = new List<Invoice__c>();
        for (Integer i = 0; i < 5; i++) {
            invoices.add(TestDataFactory.CreateInvoice(new Invoice__c(Status__c = 'Draft', Account__c = a.Id)));
            invoices.add(TestDataFactory.CreateInvoice(new Invoice__c(Status__c = 'Activated', Account__c = a.Id)));
        }
        insert invoices;
    }
    
    @isTest
    static void getInvoice_ValidId_InitializedDecorator() {
        // SETUP
        Invoice__c inv = [SELECT Id FROM Invoice__c LIMIT 1];
        // ACTION
        Invoice actual = InvoiceController.getInvoice(inv.Id);
        // VERIFY
        System.assertEquals(inv.Id, actual.Record.Id, 'Record.Id');
    }

    @isTest
    static void commitInvoiceLineItems_OnlyInsert_AllLineItemsUpdated() {
        // SETUP
        Invoice__c inv = [SELECT Id FROM Invoice__c LIMIT 1];
        List<InvoiceLineItem__c> ilisToUpsert = new List<InvoiceLineItem__c>();
        ilisToUpsert.add(TestDataFactory.CreateDefaultInvoiceLineItem());

        // ACTION
        InvoiceController.commitInvoiceLineItems(inv.Id, ilisToUpsert, new List<Id>());

        // VERIFY
        System.assertEquals(1, [SELECT COUNT() FROM InvoiceLineItem__c WHERE Invoice__c = :inv.Id], 'COUNT() FROM InvoiceLineItem__c');
    }

    @isTest
    static void commitInvoiceLineItems_UpdateAndInsert_AllLineItemsUpserted() {
        // SETUP
        Invoice__c inv = [SELECT Id FROM Invoice__c LIMIT 1];
        List<InvoiceLineItem__c> ilisToUpsert = new List<InvoiceLineItem__c>();
        InvoiceLineItem__c toUpdate = TestDataFactory.CreateInvoiceLineItem(new InvoiceLineItem__c(Invoice__c = inv.Id));
        insert toUpdate;

        InvoiceLineItem__c toInsert = TestDataFactory.CreateDefaultInvoiceLineItem();

        ilisToUpsert.add(toUpdate);
        ilisToUpsert.add(toInsert);

        // ACTION
        InvoiceController.commitInvoiceLineItems(inv.Id, ilisToUpsert, new List<Id>());

        // VERIFY
        System.assertEquals(2, [SELECT COUNT() FROM InvoiceLineItem__c WHERE Invoice__c = :inv.Id], 'COUNT() FROM InvoiceLineItem__c');
    }

    @isTest
    static void commitInvoiceLineItems_OnlyDelete_AllLineItemsDeleted() {
        // SETUP
        Invoice__c inv = [SELECT Id FROM Invoice__c LIMIT 1];
        List<InvoiceLineItem__c> ilisToUpsert = new List<InvoiceLineItem__c>();
        InvoiceLineItem__c toDelete = TestDataFactory.CreateInvoiceLineItem(new InvoiceLineItem__c(Invoice__c = inv.Id));
        insert toDelete;

        // ACTION
        InvoiceController.commitInvoiceLineItems(inv.Id, new List<InvoiceLineItem__c>(), new List<Id>{toDelete.Id});

        // VERIFY
        System.assertEquals(0, [SELECT COUNT() FROM InvoiceLineItem__c WHERE Invoice__c = :inv.Id], 'COUNT() FROM InvoiceLineItem__c');
    }

    @isTest
    static void commitInvoiceLineItems_UpdateAndDelete_AllLineItemsDeleted() {
        // SETUP
        Invoice__c inv = [SELECT Id FROM Invoice__c LIMIT 1];
        List<InvoiceLineItem__c> ilisToUpsert = new List<InvoiceLineItem__c>();
        InvoiceLineItem__c toDelete = TestDataFactory.CreateInvoiceLineItem(new InvoiceLineItem__c(Invoice__c = inv.Id));
        InvoiceLineItem__c toUpdate = TestDataFactory.CreateInvoiceLineItem(new InvoiceLineItem__c(Invoice__c = inv.Id));
        insert toDelete;

        // ACTION
        InvoiceController.commitInvoiceLineItems(inv.Id, new List<InvoiceLineItem__c>{toUpdate}, new List<Id>{toDelete.Id});

        // VERIFY
        System.assertEquals(1, [SELECT COUNT() FROM InvoiceLineItem__c WHERE Invoice__c = :inv.Id], 'COUNT() FROM InvoiceLineItem__c');
    }
}