sfdx-source/packaged/main/core/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/packaged/main/core/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>The Billing Account for this Invoice. Information from this Account are printed on the Invoice.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

sfdx-source/packaged/main/core/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/packaged/main/core/objects/InvoiceLineItem__c/InvoiceLineItem__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>OLI Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/packaged/main/core/objects/InvoiceLineItem__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <description>Percent discount given on the Amount</description>
    <inlineHelpText>Enter percent discount on Net Amount</inlineHelpText>
    <label>Discount</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
    <defaultValue>0.00</defaultValue>
</CustomField>

sfdx-source/packaged/main/core/objects/InvoiceLineItem__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

sfdx-source/packaged/main/core/objects/InvoiceLineItem__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

sfdx-source/packaged/main/core/objects/InvoiceLineItem__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

sfdx-source/packaged/main/core/classes/InvoiceLineItemTriggerHandler_Test.cls
@isTest
class InvoiceLineItemTriggerHandler_Test {
    
    @TestSetup
    static void makeData(){
        Account a = TestDataFactory.CreateDefaultAccount();
        insert a;

        Invoice__c i = TestDataFactory.CreateInvoice(new Invoice__c(Account__c = a.Id, Status__c=Constants.INVOICE_STATUS_DRAFT));
        insert i;
    }

    @isTest
    static void insert_DraftInvoice_NoSpecialPermissions_SaveSuccessful() {
        // SETUP
        User uNoPermissions = TestDataFactory.CreateDefaultUser();
        TestPermissionFactory.setupPermissions(uNoPermissions, new List<String>{'PartnerBilling_Core_FullAccess','PartnerBilling_Invoicing_FullAccess'});

        
        System.runAs(uNoPermissions) {
            System.assertEquals(false, FeatureManagement.checkPermission('Modify_Activated_Invoices'), 'checkPermission(Modify_Activated_Invoices)');
            
            // SETUP
            Account a = TestDataFactory.CreateDefaultAccount();
            insert a;
            Invoice__c i = TestDataFactory.CreateInvoice(new Invoice__c(Account__c = a.Id, Status__c=Constants.INVOICE_STATUS_DRAFT));
            insert i;
            InvoiceLineItem__c ili = TestDataFactory.CreateInvoiceLineItem(new InvoiceLineItem__c(Invoice__c=i.Id));

            // ACTION
            Database.SaveResult sr = Database.insert(ili, false);

            // VERIFY
            System.assertEquals(true, sr.isSuccess(), 'isSuccess()');
        }
    }

    @isTest
    static void insert_LockedInvoice_NoSpecialPermissions_SaveBlocked() {
        // SETUP
        User uNoPermissions = TestDataFactory.CreateDefaultUser();
        TestPermissionFactory.setupPermissions(uNoPermissions, new List<String>{'PartnerBilling_Core_FullAccess','PartnerBilling_Invoicing_FullAccess'});

        
        System.runAs(uNoPermissions) {
            System.assertEquals(false, FeatureManagement.checkPermission('Modify_Activated_Invoices'), 'checkPermission(Modify_Activated_Invoices)');
            
            // SETUP
            Account a = TestDataFactory.CreateDefaultAccount();
            insert a;
            Invoice__c i = TestDataFactory.CreateInvoice(new Invoice__c(Account__c = a.Id, Status__c=Constants.INVOICE_STATUS_ACTIVATED));
            insert i;
            InvoiceLineItem__c ili = TestDataFactory.CreateInvoiceLineItem(new InvoiceLineItem__c(Invoice__c=i.Id, Price__c = 0, Quantity__c = 0));

            // ACTION
            Database.SaveResult sr = Database.insert(ili, false);

            // VERIFY
            System.assertEquals(false, sr.isSuccess(), 'isSuccess()');
            System.assertEquals(StatusCode.FIELD_CUSTOM_VALIDATION_EXCEPTION, sr.getErrors()[0].getStatusCode(), 'sr.getErrors()[0].getStatusCode()');
            System.assertEquals(Label.Message_LineItemValidation_CanNotInsertWhenLocked, sr.getErrors()[0].getMessage(), 'sr.getErrors()[0].getMessage()');
        }
    }

    @isTest
    static void insert_LockedInvoice_HasSpecialPermissions_SaveSuccessful() {
        // SETUP
        User uHasPermissions = TestDataFactory.CreateDefaultUser();
        TestPermissionFactory.setupPermissions(uHasPermissions, new List<String>{'PartnerBilling_Core_FullAccess','PartnerBilling_Invoicing_FullAccess', 'PartnerBilling_Administrator'});

        
        System.runAs(uHasPermissions) {
            System.assertEquals(true, FeatureManagement.checkPermission('Modify_Activated_Invoices'), 'checkPermission(Modify_Activated_Invoices)');
            
            // SETUP
            Account a = TestDataFactory.CreateDefaultAccount();
            insert a;
            Invoice__c i = TestDataFactory.CreateInvoice(new Invoice__c(Account__c = a.Id, Status__c=Constants.INVOICE_STATUS_ACTIVATED));
            insert i;
            InvoiceLineItem__c ili = TestDataFactory.CreateInvoiceLineItem(new InvoiceLineItem__c(Invoice__c=i.Id, Price__c = 0, Quantity__c = 0));

            // ACTION
            Database.SaveResult sr = Database.insert(ili, false);

            // VERIFY
            System.assertEquals(true, sr.isSuccess(), 'isSuccess()');
        }
    }

    @isTest
    static void delete_DraftInvoice_NoSpecialPermissions_DeleteSuccessful() {
        // SETUP
        User uNoPermissions = TestDataFactory.CreateDefaultUser();
        TestPermissionFactory.setupPermissions(uNoPermissions, new List<String>{'PartnerBilling_Core_FullAccess','PartnerBilling_Invoicing_FullAccess'});

        System.runAs(uNoPermissions) {
            System.assertEquals(false, FeatureManagement.checkPermission('Modify_Activated_Invoices'), 'checkPermission(Modify_Activated_Invoices)');

            // SETUP
            Account a = TestDataFactory.CreateDefaultAccount();
            insert a;
            Invoice__c i = TestDataFactory.CreateInvoice(new Invoice__c(Account__c = a.Id, Status__c=Constants.INVOICE_STATUS_DRAFT));
            insert i;
            InvoiceLineItem__c ili = TestDataFactory.CreateInvoiceLineItem(new InvoiceLineItem__c(Invoice__c=i.Id, Price__c = 0, Quantity__c = 0));
            insert ili;

            // ACTION
            Database.DeleteResult dr = Database.delete(ili, false);

            // VERIFY
            System.assertEquals(true, dr.isSuccess(), 'isSuccess()');
        }
    }

    @isTest
    static void delete_LockedInvoice_NoSpecialPermissions_DeleteBlocked() {
        // SETUP
        User uNoPermissions = TestDataFactory.CreateDefaultUser();
        TestPermissionFactory.setupPermissions(uNoPermissions, new List<String>{'PartnerBilling_Core_FullAccess','PartnerBilling_Invoicing_FullAccess'});

        System.runAs(uNoPermissions) {
            System.assertEquals(false, FeatureManagement.checkPermission('Modify_Activated_Invoices'), 'checkPermission(Modify_Activated_Invoices)');

            // SETUP
            Account a = TestDataFactory.CreateDefaultAccount();
            insert a;
            Invoice__c i = TestDataFactory.CreateInvoice(new Invoice__c(Account__c = a.Id, Status__c=Constants.INVOICE_STATUS_DRAFT));
            insert i;
            InvoiceLineItem__c ili = TestDataFactory.CreateInvoiceLineItem(new InvoiceLineItem__c(Invoice__c=i.Id, Price__c = 0, Quantity__c = 0));
            insert ili;
            i.Status__c = Constants.INVOICE_STATUS_ACTIVATED;
            update i;

            // ACTION
            Database.DeleteResult dr = Database.delete(ili, false);

            // VERIFY
            System.assertEquals(false, dr.isSuccess(), 'isSuccess()');
            System.assertEquals(StatusCode.FIELD_CUSTOM_VALIDATION_EXCEPTION, dr.getErrors()[0].getStatusCode(), 'dr.getErrors()[0].getStatusCode()');
            System.assertEquals(Label.Message_LineItemValidation_CanNotDeleteWhenLocked, dr.getErrors()[0].getMessage(), 'dr.getErrors()[0].getMessage()');
        }
    }

    @isTest
    static void delete_LockedInvoice_SpecialPermissions_DeleteSuccessful() {
        // SETUP
        User uHasPermissions = TestDataFactory.CreateDefaultUser();
        TestPermissionFactory.setupPermissions(uHasPermissions, new List<String>{'PartnerBilling_Core_FullAccess','PartnerBilling_Invoicing_FullAccess','PartnerBilling_Administrator'});

        System.runAs(uHasPermissions) {
            System.assertEquals(true, FeatureManagement.checkPermission('Modify_Activated_Invoices'), 'checkPermission(Modify_Activated_Invoices)');

            // SETUP
            Account a = TestDataFactory.CreateDefaultAccount();
            insert a;
            Invoice__c i = TestDataFactory.CreateInvoice(new Invoice__c(Account__c = a.Id, Status__c=Constants.INVOICE_STATUS_DRAFT));
            insert i;
            InvoiceLineItem__c ili = TestDataFactory.CreateInvoiceLineItem(new InvoiceLineItem__c(Invoice__c=i.Id, Price__c = 0, Quantity__c = 0));
            insert ili;
            i.Status__c = Constants.INVOICE_STATUS_ACTIVATED;
            update i;

            // ACTION
            Database.DeleteResult dr = Database.delete(ili, false);

            // VERIFY
            System.assertEquals(true, dr.isSuccess(), 'isSuccess()');
        }
    }

    @isTest
    static void update_DraftInvoice_NoSpecialPermissions_SaveSuccessful() {
        // SETUP
        User uNoPermissions = TestDataFactory.CreateDefaultUser();
        TestPermissionFactory.setupPermissions(uNoPermissions, new List<String>{'PartnerBilling_Core_FullAccess','PartnerBilling_Invoicing_FullAccess'});

        
        System.runAs(uNoPermissions) {
            System.assertEquals(false, FeatureManagement.checkPermission('Modify_Activated_Invoices'), 'checkPermission(Modify_Activated_Invoices)');
            
            // SETUP
            Account a = TestDataFactory.CreateDefaultAccount();
            insert a;
            Invoice__c i = TestDataFactory.CreateInvoice(new Invoice__c(Account__c = a.Id, Status__c=Constants.INVOICE_STATUS_DRAFT));
            insert i;
            InvoiceLineItem__c ili = TestDataFactory.CreateInvoiceLineItem(new InvoiceLineItem__c(Invoice__c=i.Id, Price__c = 0, Quantity__c = 0));
            insert ili;

            // ACTION
            ili.Price__c = 100;
            ili.Quantity__c = 1;
            ili.Discount__c = 100;
            Database.SaveResult sr = Database.update(ili, false);

            // VERIFY
            System.assertEquals(true, sr.isSuccess(), 'isSuccess()');
        }
    }

    @isTest
    static void update_LockedInvoice_SpecialPermissions_UpdateSuccessful() {
        // SETUP
        User uHasPermissions = TestDataFactory.CreateDefaultUser();
        TestPermissionFactory.setupPermissions(uHasPermissions, new List<String>{'PartnerBilling_Core_FullAccess','PartnerBilling_Invoicing_FullAccess', 'PartnerBilling_Administrator'});
        
        System.runAs(uHasPermissions) {
            System.assertEquals(true, FeatureManagement.checkPermission('Modify_Activated_Invoices'), 'checkPermission(Modify_Activated_Invoices)');
            
            // SETUP
            Account a = TestDataFactory.CreateDefaultAccount();
            insert a;
            Invoice__c i = TestDataFactory.CreateInvoice(new Invoice__c(Account__c = a.Id, Status__c=Constants.INVOICE_STATUS_DRAFT));
            insert i;
            InvoiceLineItem__c ili = TestDataFactory.CreateInvoiceLineItem(new InvoiceLineItem__c(Invoice__c=i.Id, Price__c = 0, Quantity__c = 0));
            insert ili;
            i.Status__c = Constants.INVOICE_STATUS_ACTIVATED;
            update i;

            // ACTION
            ili.Price__c = 100;
            ili.Quantity__c = 1;
            ili.Discount__c = 0;
            Database.SaveResult sr = Database.update(ili, false);

            // VERIFY
            System.assertEquals(true, sr.isSuccess(), 'isSuccess()');
        }
    }

    @isTest
    static void update_LockedInvoice_NoSpecialPermissions_UpdateBlocked() {
        // SETUP
        User uNoPermissions = TestDataFactory.CreateDefaultUser();
        TestPermissionFactory.setupPermissions(uNoPermissions, new List<String>{'PartnerBilling_Core_FullAccess','PartnerBilling_Invoicing_FullAccess'});

        
        System.runAs(uNoPermissions) {
            System.assertEquals(false, FeatureManagement.checkPermission('Modify_Activated_Invoices'), 'checkPermission(Modify_Activated_Invoices)');
            
            // SETUP
            Account a = TestDataFactory.CreateDefaultAccount();
            insert a;
            Invoice__c i = TestDataFactory.CreateInvoice(new Invoice__c(Account__c = a.Id, Status__c=Constants.INVOICE_STATUS_DRAFT));
            insert i;
            InvoiceLineItem__c ili = TestDataFactory.CreateInvoiceLineItem(new InvoiceLineItem__c(Invoice__c=i.Id, Price__c = 0, Quantity__c = 0));
            insert ili;
            i.Status__c = Constants.INVOICE_STATUS_ACTIVATED;
            update i;

            // ACTION
            ili.Price__c = 100;
            ili.Quantity__c = 1;
            ili.Discount__c = 100;
            Database.SaveResult sr = Database.update(ili, false);

            // VERIFY
            System.assertEquals(false, sr.isSuccess(), 'isSuccess()');
            System.assertEquals(StatusCode.FIELD_CUSTOM_VALIDATION_EXCEPTION, sr.getErrors()[0].getStatusCode(), 'sr.getErrors()[0].getStatusCode()');
            System.assertEquals(Label.Message_LineItemValidation_CanNotEditFieldsWhenLocked, sr.getErrors()[0].getMessage(), 'sr.getErrors()[0].getMessage()');
        }
    }
}