sfdx-source/packaged/main/core/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/packaged/main/core/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>The Billing Account for this Invoice. Information from this Account are printed on the Invoice.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

sfdx-source/packaged/main/core/objects/Invoice__c/fields/OrganizationProfile__c.field-meta.xml
<CustomField>
    <fullName>OrganizationProfile__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The organization profile that is used to render the PDF and where the Invoice is billed for</description>
    <label>Organization Profile</label>
    <referenceTo>OrganizationProfile__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/packaged/main/core/objects/OrganizationProfile__c/OrganizationProfile__c.object-meta.xml
<CustomObject>
    <description>Configure and manage organization profiles. Profiles are used when generating invoice PDFs to populate the sender information.</description>
    <label>Organization Profile</label>
    <nameField>
        <label>Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organization Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/packaged/main/core/objects/OrganizationProfile__c/fields/IsDefault__c.field-meta.xml
<CustomField>
    <fullName>IsDefault__c</fullName>
    <description>Activates this profile to use as default, if the user does not have a specific profile configured.</description>
    <inlineHelpText>Use this profile as default for all users</inlineHelpText>
    <label>Is Default</label>
    <type>Checkbox</type>
    <defaultValue>true</defaultValue>
</CustomField>

sfdx-source/packaged/invoice-pdf-generation/classes/InvoicePdfController_Test.cls
@isTest
public class InvoicePdfController_Test {

    @TestSetup
    static void makeData(){
        Account a = TestDataFactory.CreateDefaultAccount();
        insert a;

        Invoice__c defaultInvoice = TestDataFactory.CreateInvoice(new Invoice__c(Account__c = a.Id));
        insert defaultInvoice;

        insert TestDataFactory.CreateDefaultOrganizationProfile();
    }

    @isTest
    static void savePdfToInvoice_MinimalInput_AttachmentAdded() {
        // SETUP
        Invoice__c record = [SELECT Id FROM Invoice__c LIMIT 1];
        OrganizationProfile__c orgProfile = [SELECT Id FROM OrganizationProfile__c LIMIT 1];

        // ACTION
        InvoicePdfController.savePdfToInvoice(record.Id, orgProfile.Id, '', null);

        // VERIFY
        System.assertEquals(0, [SELECT COUNT() FROM Attachment WHERE ParentId = :record.Id], 'COUNT() FROM Attachment');
        System.assertEquals(1, [SELECT COUNT() FROM ContentDocumentLink WHERE LinkedEntityId = :record.Id], 'COUNT() FROM ContentDocumentLink');
    }

    @isTest
    static void getOrganizationProfiles_AllOrgProfilesReturned() {
        // SETUP
        List<OrganizationProfile__c> ops = new List<OrganizationProfile__c>();
        for (Integer i = 0; i < 5; i++) {
            ops.add(TestDataFactory.CreateOrganizationProfile(new OrganizationProfile__c(Name = 'Test Profile ' + i, IsDefault__c = false)));
        }
        insert ops;

        // ACTION
        List<OrganizationProfile__c> actualOps = InvoicePdfController.getOrganizationProfiles();

        // VERIFY
        System.assertEquals([SELECT COUNT() FROM OrganizationProfile__c], actualOps.size(), 'actualOps.size()');
        OrganizationProfile__c defaultProfile = [SELECT Id FROM OrganizationProfile__c WHERE IsDefault__c = true LIMIT 1];
        System.assertEquals(defaultProfile.Id, actualOps[0].Id, 'actualOps[0].Id');
    }

    @isTest
    static void deletePdf_ValidId_VersionAndDocumentDeleted() {
        // SETUP
        Blob pdfMock = Blob.valueOf('Teststring');
        ContentVersion newVersion = new ContentVersion(Title='Test', PathOnClient='Test.pdf', VersionData=pdfMock);
        insert newVersion;
        newVersion = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :newVersion.Id];

        // ACTION
        InvoicePdfController.deletePdf(newVersion.ContentDocumentId);

        // VERIFY
        System.assertEquals(0, [SELECT COUNT() FROM ContentVersion], 'SELECT COUNT() FROM ContentVersion');
        System.assertEquals(0, [SELECT COUNT() FROM ContentDocument], 'SELECT COUNT() FROM ContentDocument');
    }
}