sfdx-source/packaged/main/core/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/packaged/main/core/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>The Billing Account for this Invoice. Information from this Account are printed on the Invoice.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

sfdx-source/packaged/main/core/objects/InvoiceLineItem__c/InvoiceLineItem__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>OLI Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/packaged/main/default/objects/InvoiceLineItem__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Short description of the invoice line item</description>
    <inlineHelpText>Enter short description of line item</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

sfdx-source/packaged/main/core/objects/InvoiceLineItem__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

sfdx-source/packaged/main/core/objects/InvoiceLineItem__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

sfdx-source/packaged/main/core/objects/InvoiceLineItem__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

sfdx-source/packaged/main/core/classes/InvoiceLineItem_Test.cls
@isTest
public class InvoiceLineItem_Test {

    @TestSetup
    static void makeData(){
        Account a = TestDataFactory.CreateDefaultAccount();
        insert a;

        Invoice__c i = TestDataFactory.CreateInvoice(new Invoice__c(Account__c = a.Id));
        insert i;
    }
    
    @isTest
    static void init_NonCommitedRecord_AllDefaultsInitialized() {
        // SETUP
        InvoiceLineItem__c ili = TestDataFactory.CreateDefaultInvoiceLineItem();
        // ACTION
        InvoiceLineItem objUnderTest = new InvoiceLineItem(ili);
        // VERIFY
        System.assertEquals(ili, objUnderTest.Record, 'Record');
        System.assertEquals(null, objUnderTest.Invoice, 'Invoice');
    }

    @isTest
    static void setInvoice_InvoiceCommited_LookupAndReferenceSet() {
        // SETUP
        Invoice__c i = [SELECT Id FROM Invoice__c LIMIT 1];
        Invoice inv = new Invoice(i.Id);
        InvoiceLineItem__c ili = TestDataFactory.CreateDefaultInvoiceLineItem();

        // ACTION
        InvoiceLineItem objUnderTest = new InvoiceLineItem(ili);
        objUnderTest.setInvoice(inv);

        // VERIFY
        System.assertEquals(inv, objUnderTest.Invoice, 'Invoice');
        System.assertEquals(i.Id, objUnderTest.Record.Invoice__c, 'Record.Invoice__c');
    }

    @isTest
    static void setInvoice_InvoiceNotCommited_OnlyReferenceSet() {
        // SETUP
        Invoice inv = new Invoice();
        InvoiceLineItem__c ili = TestDataFactory.CreateDefaultInvoiceLineItem();

        // ACTION
        InvoiceLineItem objUnderTest = new InvoiceLineItem(ili);
        objUnderTest.setInvoice(inv);

        // VERIFY
        System.assertEquals(inv, objUnderTest.Invoice, 'Invoice');
        System.assertEquals(null, objUnderTest.Record.Invoice__c, 'Record.Invoice__c');
    }

    @isTest
    static void updateRecord_ReadWriteFields_FieldsUpdated() {
        // SETUP
        InvoiceLineItem__c ili = TestDataFactory.CreateDefaultInvoiceLineItem();
        InvoiceLineItem objUnderTest = new InvoiceLineItem(ili);

        // ACTION
        objUnderTest.updateRecord(new InvoiceLineItem__c(Price__c = 0.00));

        // VERIFY
        System.assertEquals(0.00, objUnderTest.Record.Price__c, 'Record.Price__c');
        System.assertEquals(ili.Quantity__c, objUnderTest.Record.Quantity__c, 'Record.Quantity__c');
        System.assertEquals(ili.Description__c, objUnderTest.Record.Description__c, 'Record.Description__c');
    }
}