sfdx-source/packaged/main/core/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/packaged/main/core/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>The Billing Account for this Invoice. Information from this Account are printed on the Invoice.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

sfdx-source/packaged/main/core/objects/Invoice__c/fields/BillingCountry__c.field-meta.xml
<CustomField>
    <fullName>BillingCountry__c</fullName>
    <description>Billing Country of this invoice. Copied from Account&#39;s Billing Address when created</description>
    <inlineHelpText>Is copied from the Account&#39;s Billing Address</inlineHelpText>
    <label>Billing Country</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

src/packaged/main/default/objects/Invoice__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>The invoicing date</description>
    <inlineHelpText>The invoicing date that will be printed on the invoice</inlineHelpText>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

sfdx-source/packaged/main/core/objects/Invoice__c/fields/OrganizationProfile__c.field-meta.xml
<CustomField>
    <fullName>OrganizationProfile__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The organization profile that is used to render the PDF and where the Invoice is billed for</description>
    <label>Organization Profile</label>
    <referenceTo>OrganizationProfile__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/packaged/main/core/objects/Invoice__c/fields/PDFSyncSetting__c.field-meta.xml
<CustomField>
    <fullName>PDFSyncSetting__c</fullName>
    <description>Controls how the rendered PDF is handled when relevant changes are performed: Deactivated: Nothing happens, Delete: Any changes will delete all PDFs, Sync: Changes will cause an async re-render.</description>
    <inlineHelpText>Select, how changes on relevant data is handled</inlineHelpText>
    <label>PDF Sync Settings</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Deactivated</fullName>
                <default>true</default>
                <label>Deactivated</label>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Sync</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/packaged/main/core/objects/OrganizationProfile__c/OrganizationProfile__c.object-meta.xml
<CustomObject>
    <description>Configure and manage organization profiles. Profiles are used when generating invoice PDFs to populate the sender information.</description>
    <label>Organization Profile</label>
    <nameField>
        <label>Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organization Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/packaged/main/core/objects/OrganizationProfile__c/fields/IsDefault__c.field-meta.xml
<CustomField>
    <fullName>IsDefault__c</fullName>
    <description>Activates this profile to use as default, if the user does not have a specific profile configured.</description>
    <inlineHelpText>Use this profile as default for all users</inlineHelpText>
    <label>Is Default</label>
    <type>Checkbox</type>
    <defaultValue>true</defaultValue>
</CustomField>

sfdx-source/packaged/invoice-pdf-generation/classes/InvoiceTriggerHandlerPdf_Test.cls
@isTest
public class InvoiceTriggerHandlerPdf_Test {

    @TestSetup
    static void makeData(){
        Account a = TestDataFactory.CreateAccount(
            new Account(BillingStreet = 'Teststraße 1', BillingPostalCode = '80336', BillingCity = 'München', BillingCountryCode = 'DE')
        );
        insert a;

        List<OrganizationProfile__c> orgProfiles = new List<OrganizationProfile__c>();
        orgProfiles.add(TestDataFactory.CreateDefaultOrganizationProfile());
        orgProfiles.add(TestDataFactory.CreateOrganizationProfile(new OrganizationProfile__c(IsDefault__c = false, Name = 'Test Profile #1')));
        orgProfiles.add(TestDataFactory.CreateOrganizationProfile(new OrganizationProfile__c(IsDefault__c = false, Name = 'Test Profile #2')));
        insert orgProfiles;
    }
    
    @isTest
    static void update_ModifyLockedField_PdfSettingDelete_DocumentsDeleted() {
        // SETUP
        Account a = [SELECT Id FROM Account LIMIT 1];

        Invoice__c inv = TestDataFactory.CreateInvoice(new Invoice__c(Account__c = a.Id, PDFSyncSetting__c = Constants.INVOICE_PDF_SETTING_DELETE));
        insert inv;

        Blob pdfMock = Blob.valueOf('Teststring');
        ContentVersion existingVersion = new ContentVersion(Title='Test',PathOnClient='Test.pdf', VersionData=pdfMock);
        insert existingVersion;

        ContentDocument contentDoc = [SELECT Id FROM ContentDocument WHERE Title = 'Test' LIMIT 1];
        insert new ContentDocumentLink(LinkedEntityId=inv.Id, ContentDocumentId=contentDoc.Id, ShareType='V');

        // ACTION
        inv.Date__c = System.today();
        inv.BillingCountry__c = 'England';
        Database.SaveResult sr = Database.update(inv, false);

        // VERIFY
        System.assertEquals(true, sr.isSuccess(), sr.getErrors());
        System.assertEquals(0, [SELECT COUNT() FROM ContentDocument], 'COUNT() FROM ContentDocument');
    }

    @isTest
    static void update_ModifySettingToDeactivated_PdfSettingDelete_DocumentsPersist() {
        // SETUP
        Account a = [SELECT Id FROM Account LIMIT 1];

        Invoice__c inv = TestDataFactory.CreateInvoice(new Invoice__c(Account__c = a.Id, PDFSyncSetting__c = Constants.INVOICE_PDF_SETTING_DELETE));
        insert inv;

        Blob pdfMock = Blob.valueOf('Teststring');
        ContentVersion existingVersion = new ContentVersion(Title='Test',PathOnClient='Test.pdf', VersionData=pdfMock);
        insert existingVersion;

        ContentDocument contentDoc = [SELECT Id FROM ContentDocument WHERE Title = 'Test' LIMIT 1];
        insert new ContentDocumentLink(LinkedEntityId=inv.Id, ContentDocumentId=contentDoc.Id, ShareType='V');

        // ACTION
        inv.PDFSyncSetting__c = Constants.INVOICE_PDF_SETTING_DEACTIVATED;
        Database.SaveResult sr = Database.update(inv, false);

        // VERIFY
        System.assertEquals(true, sr.isSuccess(), sr.getErrors());
        System.assertEquals(1, [SELECT COUNT() FROM ContentDocument], 'COUNT() FROM ContentDocument');
    }

    @isTest
    static void update_ModifyLockedField_PdfSettingDeactivated_DocumentsPersist() {
        // SETUP
        Account a = [SELECT Id FROM Account LIMIT 1];

        Invoice__c inv = TestDataFactory.CreateInvoice(new Invoice__c(Account__c = a.Id, PDFSyncSetting__c = Constants.INVOICE_PDF_SETTING_DEACTIVATED));
        insert inv;

        Blob pdfMock = Blob.valueOf('Teststring');
        ContentVersion existingVersion = new ContentVersion(Title='Test',PathOnClient='Test.pdf', VersionData=pdfMock);
        insert existingVersion;

        ContentDocument contentDoc = [SELECT Id FROM ContentDocument WHERE Title = 'Test' LIMIT 1];
        insert new ContentDocumentLink(LinkedEntityId=inv.Id, ContentDocumentId=contentDoc.Id, ShareType='V');

        // ACTION
        inv.Date__c = System.today();
        inv.BillingCountry__c = 'England';
        Database.SaveResult sr = Database.update(inv, false);

        // VERIFY
        System.assertEquals(true, sr.isSuccess(), sr.getErrors());
        System.assertEquals(1, [SELECT COUNT() FROM ContentDocument], 'COUNT() FROM ContentDocument');
    }

    @isTest
    static void update_PdfSettingIsSync_UpdateTrackedField_NewDocumentVersionRendered() {
        // SETUP
        Account a = [SELECT Id FROM Account LIMIT 1];

        Invoice__c inv = TestDataFactory.CreateInvoice(new Invoice__c(Account__c = a.Id, PDFSyncSetting__c = Constants.INVOICE_PDF_SETTING_SYNC));
        insert inv;

        // ACTION
        Test.startTest();
        inv.Date__c = System.today();
        inv.BillingCountry__c = 'England';
        Database.SaveResult sr = Database.update(inv, false);
        Test.stopTest();

        // VERIFY
        System.assertEquals(true, sr.isSuccess(), sr.getErrors());
        System.assertEquals(1, [SELECT COUNT() FROM ContentDocument], 'COUNT() FROM ContentDocument');
    }

    @isTest
    static void update_PdfSettingIsSync_TooManyRecords_DMLError() {
        // SETUP
        Account a = [SELECT Id FROM Account LIMIT 1];

        List<Invoice__c> invs = new List<Invoice__c>();
        for (Integer i = 0; i<11; i++) {
            invs.add(TestDataFactory.CreateInvoice(new Invoice__c(Account__c = a.Id, PDFSyncSetting__c = Constants.INVOICE_PDF_SETTING_SYNC)));
        }
        insert invs;
        
        // ACTION
        Test.startTest();
        for (Invoice__c inv : invs) {
            inv.Date__c = System.today();
            inv.BillingCountry__c = 'England';
        }
        Database.SaveResult[] srs = Database.update(invs, false);
        Test.stopTest();

        // VERIFY
        for (Integer i = 0; i<10; i++) System.assertEquals(true, srs[i].isSuccess(), srs[i].getErrors());
        System.assertEquals(false, srs[10].isSuccess(), 'srs[10].isSuccess()');
        System.assertEquals(System.Label.Message_InvoiceValidation_SyncUpdateLimit, srs[10].getErrors()[0].getMessage(), 'srs[10].getErrors()[0].getMessage()');
    }
}