sfdx-source/packaged/main/core/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/packaged/main/core/objects/InvoiceLineItem__c/InvoiceLineItem__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>OLI Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/packaged/main/core/objects/InvoiceLineItem__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

sfdx-source/packaged/main/core/classes/InvoiceLineItem.cls
/** @Description
*   This is the decorator object for the custom object InvoiceLineItem__c.
*/
public class InvoiceLineItem {

    /** @Description    The decorated original SObject */
    @AuraEnabled
    public InvoiceLineItem__c Record {public get; private set;}

    /** @Description    Reference to the parent invoice of this line item */
    public Invoice Invoice {public get; private set;}

    /** @Description    Create Decorator from original SObject record */
    public InvoiceLineItem(InvoiceLineItem__c originalRecord) {
        Record = originalRecord;
    }

    /** @Description
    *   Sets the invoice lookup and the invoice id in master detail relationship.
    *   This method does not try to overwrite an existing invoice id and only works on new line items.
    *
    *   @param  parentInvoice   The invoice that will be set
    *   @return                 True, if the line item is now detail of invoice. False, if not.
    */
    public Boolean setInvoice(Invoice parentInvoice) {
        this.Invoice = parentInvoice;
        if (String.isBlank(Record.Invoice__c)) Record.Invoice__c = parentInvoice.Record.Id;
        return Record.Invoice__c == parentInvoice.Record.Id;
    }

    /** @Description
    *   Updates the internal record's fields with only those fields that
    *   are populated on the new record. Does not overwrite unpopulated fields
    *
    *   @param  newRecord   Updated record
    */
    public InvoiceLineItem__c updateRecord(InvoiceLineItem__c newRecord) {
        for (String populatedField : newRecord.getPopulatedFieldsAsMap().keySet()) {
            Record.put(populatedField, newRecord.get(populatedField));
        }
        return Record;
    }

}