sfdx-source/packaged/main/core/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/packaged/main/core/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>The Billing Account for this Invoice. Information from this Account are printed on the Invoice.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

sfdx-source/packaged/main/core/objects/Invoice__c/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <label>Total Amount (Net)</label>
    <summarizedField>InvoiceLineItem__c.Amount__c</summarizedField>
    <summaryForeignKey>InvoiceLineItem__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

src/packaged/main/default/objects/Invoice__c/fields/TotalGrossAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalGrossAmount__c</fullName>
    <label>Total Amount (Gross)</label>
    <summarizedField>InvoiceLineItem__c.GrossAmount__c</summarizedField>
    <summaryForeignKey>InvoiceLineItem__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

sfdx-source/packaged/main/core/objects/InvoiceLineItem__c/InvoiceLineItem__c.object-meta.xml
<CustomObject>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>OLI Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/packaged/main/core/objects/InvoiceLineItem__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <formula>Price__c * Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <description>Calculated "Net" amount, that is without taxes</description>
    <inlineHelpText>Net Amount (without taxes)</inlineHelpText>
    <label>Amount (Net)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

sfdx-source/packaged/main/core/objects/InvoiceLineItem__c/fields/GrossAmount__c.field-meta.xml
<CustomField>
    <fullName>GrossAmount__c</fullName>
    <formula>Amount__c * (1 + Tax__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <description>Calculated "Gross" amount, that is with taxes</description>
    <inlineHelpText>Gross Amount (including taxes)</inlineHelpText>
    <label>Amount (Gross)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

sfdx-source/packaged/main/core/objects/InvoiceLineItem__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Line Items</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

sfdx-source/packaged/main/core/objects/InvoiceLineItem__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

sfdx-source/packaged/main/core/objects/InvoiceLineItem__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

src/packaged/main/default/objects/InvoiceLineItem__c/fields/Tax__c.field-meta.xml
<CustomField>
    <fullName>Tax__c</fullName>
    <description>The tax percentage (i.e. value added tax / Mehrwertsteuer in Germany) that applies for this Line Item</description>
    <inlineHelpText>Enter the tax percentage value</inlineHelpText>
    <label>Tax</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
    <defaultValue>0.19</defaultValue>
</CustomField>

sfdx-source/packaged/main/core/objects/TimeEntry__c/TimeEntry__c.object-meta.xml
<CustomObject>
    <description>An individual time entry as unit of work that can be invoiced.</description>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>{YYYYMMDD}-{000000}</displayFormat>
        <label>Time Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/packaged/main/core/objects/TimeEntry__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The primary account where this Time Entry will be billed to</description>
    <inlineHelpText>Primary Billing Account</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>TimeEntries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/packaged/main/core/objects/TimeEntry__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Invoice that was manually or automatically created for this Time Entry. If the Invoice is set, the Time Entry is locked from modification.</description>
    <inlineHelpText>Invoice that was created from this Time Entry</inlineHelpText>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>TimeEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/packaged/main/core/objects/TimeEntry__c/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <formula>DailyRate__c * (Duration__c / 8)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

sfdx-source/packaged/main/core/classes/Invoice_Test.cls
@isTest
public class Invoice_Test {

    @TestSetup
    static void makeData(){
        Account a = TestDataFactory.CreateDefaultAccount();
        insert a;

        Invoice__c defaultInvoice = TestDataFactory.CreateInvoice(new Invoice__c(Account__c = a.Id));
        insert defaultInvoice;

        List<InvoiceLineItem__c> ilis = new List<InvoiceLineItem__c>();
        for (Integer i = 0; i < 10; i++) {
            ilis.add(TestDataFactory.CreateInvoiceLineItem(
                new InvoiceLineItem__c(Invoice__c = defaultInvoice.Id))
            );
        }
        insert ilis;
    }

    @isTest
    static void init_WithLineItems_AllDefaultsInitialized() {
        // SETUP
        Invoice__c record = [SELECT Id,(SELECT Id FROM LineItems__r) FROM Invoice__c LIMIT 1];
        // ACTION
        Invoice objUnderTest = new Invoice(record.Id);
        // VERIFY
        System.assertEquals(record.Id, objUnderTest.Record.Id, 'Record.Id');
        System.assertEquals(record.LineItems__r.size(), objUnderTest.LineItems.size(), 'LineItems.size()');
        System.assertEquals(0, objUnderTest.Record.TimeEntries__r.size(), 'Record.TimeEntries__r.size()');
    }

    @isTest
    static void init_WithoutLineItems_AllDefaultsInitialized() {
        // SETUP
        delete [SELECT Id FROM InvoiceLineItem__c];
        Invoice__c record = [SELECT Id FROM Invoice__c LIMIT 1];
        // ACTION
        Invoice objUnderTest = new Invoice(record.Id);
        // VERIFY
        System.assertEquals(record.Id, objUnderTest.Record.Id, 'Record.Id');
        System.assertEquals(0, objUnderTest.LineItems.size(), 'LineItems.size()');
        System.assertEquals(0, objUnderTest.Record.TimeEntries__r.size(), 'Record.TimeEntries__r.size()');
    }

    @isTest
    static void init_WithTimeEntries_TimesheetInitialized() {
        // SETUP
        Invoice__c record = [SELECT Id,Account__c FROM Invoice__c LIMIT 1];

        List<TimeEntry__c> tes = new List<TimeEntry__c>();
        for (Integer i = 0; i < 10; i++) {
            tes.add(TestDataFactory.CreateTimeEntry(new TimeEntry__c(Invoice__c = record.Id, Account__c = record.Account__c)));
        }
        insert tes;

        // ACTION
        Invoice objUnderTest = new Invoice(record.Id);
        
        // VERIFY
        System.assertEquals(record.Id, objUnderTest.Record.Id, 'Record.Id');
        System.assertEquals(tes.size(), objUnderTest.Record.TimeEntries__r.size(), 'Record.TimeEntries__r.size()');
    }

    @isTest
    static void init_InvalidId_EmptyInvoiceInitialized() {
        // ACTION
        Invoice actualObj = new Invoice('abc');
        // VERIFY
        System.assertEquals(new Invoice__c(), actualObj.Record, 'Invoice.Record');
        System.assertEquals(new List<InvoiceLineItem>(), actualObj.LineItems, 'Invoice.LineItems');
        System.assertEquals(new List<Attachment>(), actualObj.Attachments, 'Invoice.Attachments');
        System.assertEquals(0.0, actualObj.TotalTaxes, 'Invoice.TotalTaxes');
        System.assertEquals(0.0, actualObj.TotalTaxesPercentage, 'Invoice.TotalTaxesPercentage');
    }

    @isTest
    static void init_Null_EmptyInvoiceInitialized() {
        // SETUP
        String recordId;
        // ACTION
        Invoice actualObj = new Invoice(recordId);
        // VERIFY
        System.assertEquals(new Invoice__c(), actualObj.Record, 'Invoice.Record');
        System.assertEquals(new List<InvoiceLineItem>(), actualObj.LineItems, 'Invoice.LineItems');
        System.assertEquals(new List<Attachment>(), actualObj.Attachments, 'Invoice.Attachments');
    }

    @isTest
    static void init_BlankConstructor_EmptyInvoiceInitialized() {
        // ACTION
        Invoice actualObj = new Invoice();
        // VERIFY
        System.assertEquals(new Invoice__c(), actualObj.Record, 'Invoice.Record');
        System.assertEquals(new List<InvoiceLineItem>(), actualObj.LineItems, 'Invoice.LineItems');
        System.assertEquals(new List<Attachment>(), actualObj.Attachments, 'Invoice.Attachments');
    }

    @isTest
    static void addLineItemRecord_NewLineItem_NotAddedToPersistentLineItems() {
        // SETUP
        Invoice__c record = [SELECT Id,(SELECT Id FROM LineItems__r) FROM Invoice__c LIMIT 1];
        Invoice objUnderTest = new Invoice(record.Id);

        // ACTION
        InvoiceLineItem__c ili = TestDataFactory.CreateDefaultInvoiceLineItem();
        objUnderTest.addLineItemRecord(ili);

        // VERIFY
        System.assertEquals(record.LineItems__r.size(), objUnderTest.LineItems.size(), 'LineItems.size()');
        System.assertEquals(ili.Invoice__c, objUnderTest.Record.Id, 'Record.Id');
    }

    @isTest
    static void addLineItemRecord_ExistingLineItem_NotAddedToPersistentLineItems() {
        // SETUP
        Invoice__c record = [SELECT Id,(SELECT Id FROM LineItems__r) FROM Invoice__c LIMIT 1];
        InvoiceLineItem__c lineItemToUpdate = [SELECT Id,Price__c,Quantity__c FROM InvoiceLineItem__c WHERE Invoice__c = :record.Id LIMIT 1];
        Decimal originalQuantity = lineItemToUpdate.Quantity__c;
        Invoice objUnderTest = new Invoice(record.Id);

        // ACTION
        lineItemToUpdate.Quantity__c = 1298.98;
        objUnderTest.addLineItemRecord(lineItemToUpdate);

        // VERIFY
        System.assertEquals(record.LineItems__r.size(), objUnderTest.LineItems.size(), 'LineItems.size()');
        System.assertEquals(originalQuantity, objUnderTest.LineItemMap.get(lineItemToUpdate.Id).Record.Quantity__c, 'LineItemMap.get(lineItemToUpdate.Id).Recod.Quantity__c');
    }

    @isTest
    static void removeLineItemId_InvalidId_NoEffect() {
        // SETUP
        Invoice__c record = [SELECT Id,(SELECT Id FROM LineItems__r) FROM Invoice__c LIMIT 1];
        Invoice objUnderTest = new Invoice(record.Id);

        // ACTION
        Boolean actual = objUnderTest.removeLineItemId('a051k0000000000XXX');

        // VERIFY
        System.assertEquals(false, actual, 'return from removeLineItemId()');
    }

    @isTest
    static void removeLineItemId_ValidId_MarkedForDeletion() {
        // SETUP
        Invoice__c record = [SELECT Id,(SELECT Id FROM LineItems__r) FROM Invoice__c LIMIT 1];
        Invoice objUnderTest = new Invoice(record.Id);

        // ACTION
        Id toDeleteId = record.LineItems__r[0].Id;
        Boolean actual = objUnderTest.removeLineItemId(toDeleteId);

        // VERIFY
        System.assertEquals(true, actual, 'return from removeLineItemId()');
        System.assertEquals(true, objUnderTest.LineItemMap.containsKey(toDeleteId), 'LineItemMap.containsKey(toDeleteId)');
        System.assertEquals(record.LineItems__r.size(), objUnderTest.LineItems.size(), 'LineItems.size()');
    }

    @isTest
    static void commitAllChanges_HasNewLineItem_AddedToPersistentLineItems() {
        // SETUP
        Invoice__c record = [SELECT Id,(SELECT Id FROM LineItems__r) FROM Invoice__c LIMIT 1];
        Invoice objUnderTest = new Invoice(record.Id);
        InvoiceLineItem__c ili = TestDataFactory.CreateDefaultInvoiceLineItem();
        objUnderTest.addLineItemRecord(ili);

        // ACTION
        objUnderTest.commitAllChanges();

        // VERIFY
        System.assertEquals(record.LineItems__r.size() + 1, objUnderTest.LineItems.size(), 'LineItems.size()');
        System.assertNotEquals(null, ili.Id, 'ili.Record.Id');
    }

    @isTest
    static void commitAllChanges_ExistingNewLineItem_PersistentLineItemsUpdated() {
        // SETUP
        Invoice__c record = [SELECT Id,(SELECT Id FROM LineItems__r) FROM Invoice__c LIMIT 1];
        InvoiceLineItem__c lineItemToUpdate = [SELECT Id FROM InvoiceLineItem__c WHERE Invoice__c = :record.Id LIMIT 1];
        Invoice objUnderTest = new Invoice(record.Id);
        lineItemToUpdate.Quantity__c = 100;
        lineItemToUpdate.Price__c = 999.12;
        objUnderTest.addLineItemRecord(lineItemToUpdate);

        // ACTION
        objUnderTest.commitAllChanges();

        // VERIFY
        System.assertEquals(record.LineItems__r.size(), objUnderTest.LineItems.size(), 'LineItems.size()');
        System.assertEquals(lineItemToUpdate.Quantity__c, objUnderTest.LineItemMap.get(lineItemToUpdate.Id).Record.Quantity__c, 'LineItemMap.get(lineItemToUpdate.Id).Record.Quantity__c');
        System.assertEquals(lineItemToUpdate.Price__c, objUnderTest.LineItemMap.get(lineItemToUpdate.Id).Record.Price__c, 'LineItemMap.get(lineItemToUpdate.Id).Record.Price__c');
    }

    @isTest
    static void commitAllChanges_LineItemMarkedForDeletion_LineItemDeleted() {
        // SETUP
        Invoice__c record = [SELECT Id,(SELECT Id FROM LineItems__r) FROM Invoice__c LIMIT 1];
        Invoice objUnderTest = new Invoice(record.Id);
        Id toDeleteId = record.LineItems__r[0].Id;
        objUnderTest.removeLineItemId(toDeleteId);

        // ACTION
        objUnderTest.commitAllChanges();

        // VERIFY
        System.assertEquals(false, objUnderTest.LineItemMap.containsKey(toDeleteId), 'LineItemMap.containsKey(toDeleteId)');
        System.assertEquals(record.LineItems__r.size() - 1, objUnderTest.LineItems.size(), 'LineItems.size()');
    }

    /**                             GETTER & SETTER
    *   - calculated taxes based on invoice net/gross
    *
    *
    */
    
    @isTest
    static void getTaxes_MixedPercentagesInLineItems_CorrectlyCalculated() {
        // SETUP
        Account a = [SELECT Id FROM Account LIMIT 1];
        Invoice__c defaultInvoice = TestDataFactory.CreateInvoice(new Invoice__c(Account__c = a.Id));
        insert defaultInvoice;

        List<InvoiceLineItem__c> ilis = new List<InvoiceLineItem__c>();
        ilis.add(TestDataFactory.CreateInvoiceLineItem(new InvoiceLineItem__c(Invoice__c = defaultInvoice.Id, Tax__c=10, Price__c=750, Quantity__c=1)));
        ilis.add(TestDataFactory.CreateInvoiceLineItem(new InvoiceLineItem__c(Invoice__c = defaultInvoice.Id, Tax__c=20, Price__c=750, Quantity__c=1)));
        ilis.add(TestDataFactory.CreateInvoiceLineItem(new InvoiceLineItem__c(Invoice__c = defaultInvoice.Id, Tax__c=19, Price__c=1250, Quantity__c=3)));
        insert ilis;

        // ACTION
        Invoice invObj = new Invoice(defaultInvoice.Id);

        // VERIFY
        System.assertEquals(5250, invObj.Record.TotalAmount__c, 'Record.Amount__c');
        System.assertEquals(6187.50, invObj.Record.TotalGrossAmount__c, 'Record.GrossAmount__c');
        System.assertEquals(937.50, invObj.TotalTaxes, 'TotalTaxes');
        System.assertEquals(0.1786, invObj.TotalTaxesPercentage, 'TotalTaxesPercentage');
    }
}