sfdx-source/packaged/main/core/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/packaged/main/core/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>The Billing Account for this Invoice. Information from this Account are printed on the Invoice.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

sfdx-source/packaged/main/core/objects/Invoice__c/fields/BillingCity__c.field-meta.xml
<CustomField>
    <fullName>BillingCity__c</fullName>
    <description>Billing City of this invoice. Copied from Account&#39;s Billing Address when created</description>
    <inlineHelpText>Is copied from the Account&#39;s Billing Address</inlineHelpText>
    <label>Billing City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfdx-source/packaged/main/core/objects/Invoice__c/fields/BillingCountry__c.field-meta.xml
<CustomField>
    <fullName>BillingCountry__c</fullName>
    <description>Billing Country of this invoice. Copied from Account&#39;s Billing Address when created</description>
    <inlineHelpText>Is copied from the Account&#39;s Billing Address</inlineHelpText>
    <label>Billing Country</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

sfdx-source/packaged/main/core/objects/Invoice__c/fields/BillingPostalCode__c.field-meta.xml
<CustomField>
    <fullName>BillingPostalCode__c</fullName>
    <description>Billing Postalcode of this invoice. Copied from Account's Billing Address when created</description>
    <inlineHelpText>Is copied from the Account's Billing Address</inlineHelpText>
    <label>Billing Postal Code</label>
    <type>Text</type>
    <length>50</length>
</CustomField>

sfdx-source/packaged/main/core/objects/Invoice__c/fields/BillingState__c.field-meta.xml
<CustomField>
    <fullName>BillingState__c</fullName>
    <description>Billing State of this invoice. Copied from Account's Billing Address when created</description>
    <inlineHelpText>Is copied from the Account's Billing Address</inlineHelpText>
    <label>Billing State</label>
    <type>Text</type>
    <length>100</length>
</CustomField>

sfdx-source/packaged/main/core/objects/Invoice__c/fields/BillingStreet__c.field-meta.xml
<CustomField>
    <fullName>BillingStreet__c</fullName>
    <description>Billing Street of this invoice. Copied from Account&#39;s Billing Address when created</description>
    <inlineHelpText>Is copied from the Account&#39;s Billing Address</inlineHelpText>
    <label>Billing Street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdx-source/packaged/main/core/objects/Invoice__c/fields/OrganizationProfile__c.field-meta.xml
<CustomField>
    <fullName>OrganizationProfile__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The organization profile that is used to render the PDF and where the Invoice is billed for</description>
    <label>Organization Profile</label>
    <referenceTo>OrganizationProfile__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/packaged/main/core/objects/Invoice__c/fields/PDFSyncSetting__c.field-meta.xml
<CustomField>
    <fullName>PDFSyncSetting__c</fullName>
    <description>Controls how the rendered PDF is handled when relevant changes are performed: Deactivated: Nothing happens, Delete: Any changes will delete all PDFs, Sync: Changes will cause an async re-render.</description>
    <inlineHelpText>Select, how changes on relevant data is handled</inlineHelpText>
    <label>PDF Sync Settings</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Deactivated</fullName>
                <default>true</default>
                <label>Deactivated</label>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Sync</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/packaged/main/core/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/packaged/main/core/objects/OrganizationProfile__c/OrganizationProfile__c.object-meta.xml
<CustomObject>
    <description>Configure and manage organization profiles. Profiles are used when generating invoice PDFs to populate the sender information.</description>
    <label>Organization Profile</label>
    <nameField>
        <label>Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organization Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/packaged/main/core/objects/OrganizationProfile__c/fields/IsDefault__c.field-meta.xml
<CustomField>
    <fullName>IsDefault__c</fullName>
    <description>Activates this profile to use as default, if the user does not have a specific profile configured.</description>
    <inlineHelpText>Use this profile as default for all users</inlineHelpText>
    <label>Is Default</label>
    <type>Checkbox</type>
    <defaultValue>true</defaultValue>
</CustomField>

sfdx-source/packaged/main/core/objects/TimeEntry__c/TimeEntry__c.object-meta.xml
<CustomObject>
    <description>An individual time entry as unit of work that can be invoiced.</description>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>{YYYYMMDD}-{000000}</displayFormat>
        <label>Time Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/packaged/main/core/objects/TimeEntry__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The primary account where this Time Entry will be billed to</description>
    <inlineHelpText>Primary Billing Account</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>TimeEntries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/packaged/main/core/objects/TimeEntry__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Invoice that was manually or automatically created for this Time Entry. If the Invoice is set, the Time Entry is locked from modification.</description>
    <inlineHelpText>Invoice that was created from this Time Entry</inlineHelpText>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>TimeEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/packaged/main/core/objects/TimeEntry__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/packaged/main/core/classes/InvoiceTriggerHandler.cls
public with sharing class InvoiceTriggerHandler implements ITriggerHandler {

    private List<TimeEntry__c> TimeEntriesToUpdate = new List<TimeEntry__c>();
    private List<ContentDocument> DocumentsToDelete = new List<ContentDocument>();

    /** @Description    All time entries (time sheets), mapped by invoice id. Lazy init. */
    private Map<Id, List<TimeEntry__c>> TimeEntries {
        private get {
            if (TimeEntries == null) {
                TimeEntries = new Map<Id, List<TimeEntry__c>>();
                if (Trigger.isUpdate) {
                    for (Invoice__c inv : [SELECT Id,(SELECT Id FROM TimeEntries__r) FROM Invoice__c WHERE Id IN :Trigger.oldMap.keySet()]) {
                        TimeEntries.put(inv.Id, inv.TimeEntries__r);
                    }
                }
            }
            return TimeEntries;
        }
        private set;
    }

    /** @Description    All related parent accounts to invoices. Lazy init. */
    private Map<Id, Account> Accounts {
        private get {
            if (Accounts == null) {
                // extract account ids from invoice and load accounts
                Set<Id> AccountIds = new Set<Id>();
                if (Trigger.new != null) {
                    for (Invoice__c inv : (List<Invoice__c>)Trigger.new) AccountIds.add(inv.Account__c);
                }
                Accounts = new Map<Id, Account>([SELECT Id,Name,BillingAddress FROM Account WHERE Id IN :AccountIds]);
            }
            return Accounts;
        }
        private set;
    }

    /** @Description    All org profiles that are available for the current user */
    private Map<Id, OrganizationProfile__c> OrganizationProfiles {
        private get {
            if (OrganizationProfiles == null) {
                OrganizationProfiles = new Map<Id, OrganizationProfile__c>(
                    [SELECT Id,Name,IsDefault__c
                    FROM OrganizationProfile__c ORDER BY IsDefault__c DESC]
                );
            }
            return OrganizationProfiles;
        }
        private set;
    }

    /** @Description    All content document links mapped by invoice id */
    private Map<Id, List<ContentDocumentLink>> Documents {
        private get {
            if (Documents == null) {
                Documents = new Map<Id, List<ContentDocumentLink>>();
                if (Trigger.isUpdate) {
                    for (Invoice__c inv : [SELECT Id,(SELECT Id,ContentDocumentId,ContentDocument.Title FROM ContentDocumentLinks) FROM Invoice__c WHERE Id IN :Trigger.oldMap.keySet()]) {
                        Documents.put(inv.Id, inv.ContentDocumentLinks);
                    }
                }
            }
            return Documents;
        }
        private set;
    }

    public InvoiceTriggerHandler() { }

    /** @Description
    *   Implementation of ITriggerHandler interface. Entry point to execute all trigger logic.
    *   This method solves trigger context and bulkification and dispatches to more specific functions
    *   to implement the individually needed logic.
    */
    public void execute() {
        if (!Trigger.isExecuting) return;
        switch on Trigger.OperationType {
            when BEFORE_INSERT { for (SObject so : Trigger.new) beforeInsert((Invoice__c)so); }
            when AFTER_UPDATE { for (SObject so : Trigger.new) afterUpdate((Invoice__c)so, (Invoice__c)(Trigger.oldMap.get(so.Id))); }
            when BEFORE_UPDATE { for (SObject so : Trigger.new) beforeUpdate((Invoice__c)so, (Invoice__c)(Trigger.oldMap.get(so.Id))); }
        }
        commitRelatedRecords();
    }

    /** @Description
    *   The beforeInsert scope method only defines order of execution for the business
    *   methods it calls
    */
    public void beforeInsert(Invoice__c newSo) {
        copyBillingAddressFromAccount(newSo);
        prefillDefaultOrgProfileId(newSo);
    }

    /** @Description
    *   All functionality that runs in after update scope. Order of execution is defined here.
    */
    public void afterUpdate(Invoice__c newSo, Invoice__c oldSo) {
        removeTimesheetFromCancelledInvoice(newSo);
        removeDocumentsFromDeleteConfiguredInvoice(newSo);
    }

    /** @Description
    *   All functionality that runs in before update scope. Order of execution is defined here.
    */
    public void beforeUpdate(Invoice__c newSo, Invoice__c oldSo) {
        validateModifications(new Invoice(newSo), new Invoice(oldSo));
    }

    /** @Description
    *   Commit all related records that have been cached
    */
    public void commitRelatedRecords() {
        Database.update(TimeEntriesToUpdate, true);
        Database.delete(DocumentsToDelete, true);
    }

    /**                                 PRIVATE METHODS                                      */

    private void copyBillingAddressFromAccount(Invoice__c newInvoice) {
        if (Accounts.containsKey(newInvoice.Account__c) && Accounts.get(newInvoice.Account__c).BillingAddress != null) {
            Address addr = Accounts.get(newInvoice.Account__c).BillingAddress;
            newInvoice.BillingStreet__c = String.isNotBlank(newInvoice.BillingStreet__c) ? newInvoice.BillingStreet__c : addr.getStreet();
            newInvoice.BillingPostalCode__c = String.isNotBlank(newInvoice.BillingPostalCode__c) ? newInvoice.BillingPostalCode__c : addr.getPostalCode();
            newInvoice.BillingCity__c = String.isNotBlank(newInvoice.BillingCity__c) ? newInvoice.BillingCity__c : addr.getCity();
            newInvoice.BillingCountry__c = String.isNotBlank(newInvoice.BillingCountry__c) ? newInvoice.BillingCountry__c : addr.getCountry();
            newInvoice.BillingState__c = String.isNotBlank(newInvoice.BillingState__c) ? newInvoice.BillingState__c : addr.getState();
        }
    }

    private void removeTimesheetFromCancelledInvoice(Invoice__c inv) {
        if (inv.Status__c == Constants.INVOICE_STATUS_CANCELLED) {
            for (TimeEntry__c te : TimeEntries.get(inv.Id)) {
                te.Invoice__c = null;
            }
            TimeEntriesToUpdate.addAll(TimeEntries.get(inv.Id));
        }
    }

    private void validateModifications(Invoice newInvoice, Invoice oldInvoice) {
        for (String fieldName : Invoice.ACTIVATED_LOCKED_FIELDS) {
            if (newInvoice.Record.get(fieldName) != oldInvoice.Record.get(fieldName) && oldInvoice.IsLocked) {
                if (!FeatureManagement.checkPermission('Modify_Activated_Invoices')) {
                    newInvoice.Record.addError(Label.Message_InvoiceValidation_CanNotEditLockedField);
                    break;
                }
            }
        }
    }

    private void prefillDefaultOrgProfileId(Invoice__c newRecord) {
        if (!OrganizationProfiles.isEmpty()) {
            newRecord.OrganizationProfile__c = OrganizationProfiles.values()[0].Id;
        }
    }

    private void removeDocumentsFromDeleteConfiguredInvoice(Invoice__c newRecord) {
        if (newRecord.PDFSyncSetting__c == Constants.INVOICE_PDF_SETTING_DELETE) {
            for (ContentDocumentLink cdl : Documents.get(newRecord.Id)) {
                DocumentsToDelete.add(cdl.ContentDocument);
            }
        }
    }
}