sfdx-source/packaged/main/core/objects/TimeEntry__c/TimeEntry__c.object-meta.xml
<CustomObject>
    <description>An individual time entry as unit of work that can be invoiced.</description>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>{YYYYMMDD}-{000000}</displayFormat>
        <label>Time Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/packaged/main/core/objects/TimeEntry__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The primary account where this Time Entry will be billed to</description>
    <inlineHelpText>Primary Billing Account</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>TimeEntries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

src/packaged/main/default/objects/TimeEntry__c/fields/EndTime__c.field-meta.xml
<CustomField>
    <fullName>EndTime__c</fullName>
    <description>Time when work was finished. Used to calculate duration.</description>
    <inlineHelpText>Time when work was finished.</inlineHelpText>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

src/packaged/time-tracking/classes/TimeTrackingController_Test.cls
@isTest
class TimeTrackingController_Test {

    @TestSetup
    static void makeData(){
        insert TestDataFactory.CreateDefaultAccount();
    }

    @isTest
    static void getUnfinishedTimeEntries_NoTimeEntries_EmptyList() {
        // ACTION
        List<TimeEntry__c> tes = TimeTrackingController.getUnfinishedTimeEntries();
        // VERIFY
        System.assertEquals(0, tes.size(), 'tes.size()');
    }

    @isTest
    static void getUnfinishedTimeEntries_NoUnfinishedTimeEntries_EmptyList() {
        // SETUP
        Account a = [SELECT Id FROM Account LIMIT 1];
        List<TimeEntry__c> tes = new List<TimeEntry__c>();
        tes.add(TestDataFactory.CreateTimeEntry(new TimeEntry__c(Account__c = a.Id, EndTime__c = Time.newInstance(18, 0, 0, 0))));
        tes.add(TestDataFactory.CreateTimeEntry(new TimeEntry__c(Account__c = a.Id, EndTime__c = Time.newInstance(18, 0, 0, 0))));
        insert tes;
        // ACTION
        List<TimeEntry__c> actualTes = TimeTrackingController.getUnfinishedTimeEntries();
        // VERIFY
        System.assertEquals(0, actualTes.size(), 'actualTes.size()');
    }

    @isTest
    static void getUnfinishedTimeEntries_WithUnfinishedTimeEntries_OnlyUnfinishedTimeEntries() {
        // SETUP
        Account a = [SELECT Id FROM Account LIMIT 1];
        List<TimeEntry__c> tes = new List<TimeEntry__c>();
        tes.add(TestDataFactory.CreateTimeEntry(new TimeEntry__c(Account__c = a.Id, EndTime__c = Time.newInstance(18, 0, 0, 0))));
        tes.add(TestDataFactory.CreateTimeEntry(new TimeEntry__c(Account__c = a.Id, EndTime__c = null)));
        insert tes;
        // ACTION
        List<TimeEntry__c> actualTes = TimeTrackingController.getUnfinishedTimeEntries();
        // VERIFY
        System.assertEquals(1, actualTes.size(), 'actualTes.size()');
    }
    
}