sfdx-source/packaged/main/core/objects/TimeEntry__c/TimeEntry__c.object-meta.xml
<CustomObject>
    <description>An individual time entry as unit of work that can be invoiced.</description>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>{YYYYMMDD}-{000000}</displayFormat>
        <label>Time Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/packaged/main/default/objects/TimeEntry__c/fields/EndTime__c.field-meta.xml
<CustomField>
    <fullName>EndTime__c</fullName>
    <description>Time when work was finished. Used to calculate duration.</description>
    <inlineHelpText>Time when work was finished.</inlineHelpText>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

src/packaged/time-tracking/classes/TimeTrackingController.cls
/** @Description
*   Static UI API for time tracking functionality */
public with sharing class TimeTrackingController {

    /** @Description
    *   Retrieves List of non-ended / unfinished time entries (Ids only) for the current user.
    *   The Time Entries are ordered by created date (most recent first)
    *
    *   @return             List of unfinished Time Entries.
    */
    @AuraEnabled(cacheable=true)
    public static List<TimeEntry__c> getUnfinishedTimeEntries(){
        return [SELECT Id
                FROM TimeEntry__c WHERE OwnerId = :UserInfo.getUserId() AND EndTime__c = null
                ORDER BY CreatedDate DESC];
    }

}