sfdx-source/packaged/main/core/objects/Budget__c/Budget__c.object-meta.xml
<CustomObject>
    <description>Individually controlled budgets for customers (i.e. for projects or specific time periods)</description>
    <label>Budget</label>
    <nameField>
        <label>Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/packaged/main/default/objects/Budget__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The primary account that holds this Budget</description>
    <inlineHelpText>Primary Billing Account</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Budgets</relationshipLabel>
    <relationshipName>Budgets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/packaged/main/core/objects/Budget__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/packaged/main/core/objects/Budget__c/fields/TotalAmountInvoiced__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountInvoiced__c</fullName>
    <label>Total Ampount Invoiced</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
    <description>Sum of all invoiced time entries (calculated amount) for this Budget</description>
    <inlineHelpText>Sum of amount for all invoiced Time Entries to this Budget</inlineHelpText>
</CustomField>

sfdx-source/packaged/main/core/objects/Budget__c/fields/TotalAmountLogged__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountLogged__c</fullName>
    <label>Total Ampount Logged</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
    <description>Sum of all time entries (calculated amount) for this Budget</description>
    <inlineHelpText>Sum of amount for all Time Entries to this Budget</inlineHelpText>
</CustomField>

sfdx-source/packaged/main/core/objects/TimeEntry__c/TimeEntry__c.object-meta.xml
<CustomObject>
    <description>An individual time entry as unit of work that can be invoiced.</description>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>{YYYYMMDD}-{000000}</displayFormat>
        <label>Time Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/packaged/main/core/objects/TimeEntry__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The primary account where this Time Entry will be billed to</description>
    <inlineHelpText>Primary Billing Account</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>TimeEntries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/packaged/main/core/objects/TimeEntry__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Add this time entry to a budget to roll up costs</description>
    <label>Budget</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Budget must be related to the same Account</errorMessage>
        <filterItems>
            <field>Budget__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <infoMessage>Select a Budget from the same Account</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Budget__c</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>TimeEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/packaged/main/core/objects/TimeEntry__c/fields/DailyRate__c.field-meta.xml
<CustomField>
    <fullName>DailyRate__c</fullName>
    <label>Daily Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

sfdx-source/packaged/main/core/objects/TimeEntry__c/fields/EndTime__c.field-meta.xml
<CustomField>
    <fullName>EndTime__c</fullName>
    <description>Time when work was finished. Used to calculate duration.</description>
    <inlineHelpText>Time when work was finished.</inlineHelpText>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

sfdx-source/packaged/main/core/objects/TimeEntry__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <description>Time when work started. Will be used to calculate duration</description>
    <inlineHelpText>Time when work started</inlineHelpText>
    <label>Start Time</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

sfdx-source/packaged/main/core/objects/TimeEntry__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/packaged/main/core/classes/TimeEntryTriggerHandler_Test.cls
@isTest
public class TimeEntryTriggerHandler_Test {
    
    @TestSetup
    static void makeData(){
        Account a = TestDataFactory.CreateDefaultAccount();
        insert a;

        Budget__c b = TestDataFactory.CreateBudget(new Budget__c(Account__c = a.Id));
        insert b;   
    }

    @isTest
    static void insert_NewTimeEntry_BudgetSummaryRecalculated() {
        // SETUP
        Budget__c b = [SELECT Id,Account__c FROM Budget__c LIMIT 1];
        TimeEntry__c toInsert = TestDataFactory.CreateTimeEntry(
            new TimeEntry__c(
                Budget__c = b.Id,
                Account__c = b.Account__c,
                DailyRate__c = 1500.00,
                StartTime__c = Time.newInstance(8,0,0,0),
                EndTime__c = Time.newInstance(12,0,0,0),
                Status__c = 'New')
        );

        // ACTION
        Database.SaveResult sr = Database.insert(toInsert, false);

        // VERIFY
        System.assertEquals(true, sr.isSuccess(), sr.getErrors());
        Budget__c newBudget = [SELECT Id,TotalAmountLogged__c,TotalAmountInvoiced__c FROM Budget__c WHERE Id = :b.Id];
        System.assertEquals(750.00, newBudget.TotalAmountLogged__c, 'TotalAmountLogged__c');
        System.assertEquals(0, newBudget.TotalAmountInvoiced__c, 'TotalAmountInvoiced__c');
    }

    @isTest
    static void insert_InvoicedTimeEntry_BudgetSummaryRecalculated() {
        // SETUP
        Budget__c b = [SELECT Id,Account__c FROM Budget__c LIMIT 1];
        TimeEntry__c toInsert = TestDataFactory.CreateTimeEntry(
            new TimeEntry__c(
                Budget__c = b.Id,
                Account__c = b.Account__c,
                DailyRate__c = 1500.00,
                StartTime__c = Time.newInstance(8,0,0,0),
                EndTime__c = Time.newInstance(12,0,0,0),
                Status__c = 'Invoiced')
        );

        // ACTION
        Database.SaveResult sr = Database.insert(toInsert, false);

        // VERIFY
        System.assertEquals(true, sr.isSuccess(), sr.getErrors());
        Budget__c newBudget = [SELECT Id,TotalAmountLogged__c,TotalAmountInvoiced__c FROM Budget__c WHERE Id = :b.Id];
        System.assertEquals(750.00, newBudget.TotalAmountLogged__c, 'TotalAmountLogged__c');
        System.assertEquals(750.00, newBudget.TotalAmountInvoiced__c, 'TotalAmountInvoiced__c');
    }

    @isTest
    static void update_ChangeTotalAmount_BudgetSummaryRecalculated() {
        
    }

    @isTest
    static void delete_ValidTimeEntry_BudgetSummaryRecalculated() {
        
    }
}