sfdx-source/packaged/main/core/objects/Budget__c/Budget__c.object-meta.xml
<CustomObject>
    <description>Individually controlled budgets for customers (i.e. for projects or specific time periods)</description>
    <label>Budget</label>
    <nameField>
        <label>Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/packaged/main/default/objects/Budget__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The primary account that holds this Budget</description>
    <inlineHelpText>Primary Billing Account</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Budgets</relationshipLabel>
    <relationshipName>Budgets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/packaged/main/core/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/packaged/main/core/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>The Billing Account for this Invoice. Information from this Account are printed on the Invoice.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

src/packaged/main/default/objects/Invoice__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>The invoicing date</description>
    <inlineHelpText>The invoicing date that will be printed on the invoice</inlineHelpText>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

sfdx-source/packaged/main/core/objects/Invoice__c/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <label>Total Amount (Net)</label>
    <summarizedField>InvoiceLineItem__c.Amount__c</summarizedField>
    <summaryForeignKey>InvoiceLineItem__c.Invoice__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

sfdx-source/packaged/main/core/objects/TimeEntry__c/TimeEntry__c.object-meta.xml
<CustomObject>
    <description>An individual time entry as unit of work that can be invoiced.</description>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>{YYYYMMDD}-{000000}</displayFormat>
        <label>Time Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/packaged/main/core/objects/TimeEntry__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The primary account where this Time Entry will be billed to</description>
    <inlineHelpText>Primary Billing Account</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>TimeEntries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/packaged/main/core/objects/TimeEntry__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Add this time entry to a budget to roll up costs</description>
    <label>Budget</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Budget must be related to the same Account</errorMessage>
        <filterItems>
            <field>Budget__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <infoMessage>Select a Budget from the same Account</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Budget__c</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>TimeEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/packaged/main/core/objects/TimeEntry__c/fields/DailyRate__c.field-meta.xml
<CustomField>
    <fullName>DailyRate__c</fullName>
    <label>Daily Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

sfdx-source/packaged/main/core/objects/TimeEntry__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>The calender date where this time entry / work occured</description>
    <inlineHelpText>Calender date where work was done</inlineHelpText>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

src/packaged/main/default/objects/TimeEntry__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Short description of the performed work</description>
    <inlineHelpText>Enter short description of the work performed</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

sfdx-source/packaged/main/core/objects/TimeEntry__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>Calculated duration in decimal hour format (3 hours 30 minutes = 3,5)</description>
    <formula>(HOUR(EndTime__c) - HOUR(StartTime__c)) + (MINUTE(EndTime__c)-MINUTE(StartTime__c)) / 60</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Calculated duration</inlineHelpText>
    <label>Duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/packaged/main/default/objects/TimeEntry__c/fields/EndTime__c.field-meta.xml
<CustomField>
    <fullName>EndTime__c</fullName>
    <description>Time when work was finished. Used to calculate duration.</description>
    <inlineHelpText>Time when work was finished.</inlineHelpText>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

src/packaged/main/default/objects/TimeEntry__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Invoice that was manually or automatically created for this Time Entry. If the Invoice is set, the Time Entry is locked from modification.</description>
    <inlineHelpText>Invoice that was created from this Time Entry</inlineHelpText>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>TimeEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/packaged/main/core/objects/TimeEntry__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>TimeEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/packaged/main/core/objects/TimeEntry__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <description>Time when work started. Will be used to calculate duration</description>
    <inlineHelpText>Time when work started</inlineHelpText>
    <label>Start Time</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

src/packaged/main/default/objects/TimeEntry__c/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <formula>DailyRate__c * (Duration__c / 8)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/packaged/main/default/classes/TimeEntry_Test.cls
@isTest
public class TimeEntry_Test {

    @TestSetup
    static void makeData(){
        Account a = TestDataFactory.CreateDefaultAccount();
        insert a;

        Budget__c b = TestDataFactory.CreateBudget(new Budget__c(Account__c = a.Id));
        insert b;

        Invoice__c i = TestDataFactory.CreateInvoice(new Invoice__c(Account__c = a.Id));
        insert i;

        Product2 p = TestDataFactory.CreateDefaultProduct();
        insert p;
    }
    
    @isTest
    static void init_ValidRecord_AllDefaultsInitialized() {
        // SETUP
        Account a = [SELECT Id,Name FROM Account LIMIT 1];
        Budget__c b = [SELECT Id FROM Budget__c LIMIT 1];
        Invoice__c i = [SELECT Id FROM Invoice__c LIMIT 1];
        Product2 p = [SELECT Id,Name FROM Product2 LIMIT 1];

        TimeEntry__c te = TestDataFactory.CreateTimeEntry(
            new TimeEntry__c(
                Account__c = a.Id,
                Budget__c = b.Id,
                Invoice__c = i.Id,
                Product__c = p.Id
            )
        );
        insert te;

        // ACTION
        te = Database.Query(TimeEntry.QUERY_STRING + ' LIMIT 1');
        TimeEntry objUnderTest = new TimeEntry(te);

        // VERIFY
        System.assertEquals(a.Name, objUnderTest.AccountName, 'AccountName');
        System.assertEquals(p.Name, objUnderTest.ProductName, 'ProductName');
        System.assertEquals(te.Name, objUnderTest.Name, 'Name');
        System.assertEquals(te.Id, objUnderTest.Id, 'Id');
        System.assertEquals(te.Duration__c + ' h', objUnderTest.Duration, 'Duration');
        System.assertEquals(te.StartTime__c, objUnderTest.StartTime, 'StartTime');
        System.assertEquals(te.EndTime__c, objUnderTest.EndTime, 'EndTime');
        System.assertEquals(te.TotalAmount__c, objUnderTest.TotalAmount, 'TotalAmount');
        System.assertEquals(te.DailyRate__c, objUnderTest.DailyRate, 'DailyRate');
        System.assertEquals(te.Date__c, objUnderTest.ServiceDate, 'ServiceDate');
        System.assertEquals(te.Description__c, objUnderTest.Description, 'Description');
    }
}