sfdx-source/packaged/main/core/objects/Budget__c/Budget__c.object-meta.xml
<CustomObject>
    <description>Individually controlled budgets for customers (i.e. for projects or specific time periods)</description>
    <label>Budget</label>
    <nameField>
        <label>Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/packaged/main/default/objects/Budget__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The primary account that holds this Budget</description>
    <inlineHelpText>Primary Billing Account</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Budgets</relationshipLabel>
    <relationshipName>Budgets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/packaged/main/core/objects/Budget__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/packaged/main/default/objects/Budget__c/fields/TotalAmountInvoiced__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountInvoiced__c</fullName>
    <label>Total Amount Invoiced</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
    <description>Sum of all invoiced time entries (calculated amount) for this Budget</description>
    <inlineHelpText>Sum of amount for all invoiced Time Entries to this Budget</inlineHelpText>
</CustomField>

src/packaged/main/default/objects/Budget__c/fields/TotalAmountLogged__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountLogged__c</fullName>
    <label>Total Amount Logged</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
    <description>Sum of all time entries (calculated amount) for this Budget</description>
    <inlineHelpText>Sum of amount for all Time Entries to this Budget</inlineHelpText>
</CustomField>

sfdx-source/packaged/main/core/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{000000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

sfdx-source/packaged/main/core/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>The Billing Account for this Invoice. Information from this Account are printed on the Invoice.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

sfdx-source/packaged/main/core/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Activated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdx-source/packaged/main/core/objects/TimeEntry__c/TimeEntry__c.object-meta.xml
<CustomObject>
    <description>An individual time entry as unit of work that can be invoiced.</description>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>{YYYYMMDD}-{000000}</displayFormat>
        <label>Time Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/packaged/main/core/objects/TimeEntry__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The primary account where this Time Entry will be billed to</description>
    <inlineHelpText>Primary Billing Account</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>TimeEntries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/packaged/main/core/objects/TimeEntry__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Add this time entry to a budget to roll up costs</description>
    <label>Budget</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Budget must be related to the same Account</errorMessage>
        <filterItems>
            <field>Budget__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <infoMessage>Select a Budget from the same Account</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Budget__c</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>TimeEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/packaged/main/core/objects/TimeEntry__c/fields/DailyRate__c.field-meta.xml
<CustomField>
    <fullName>DailyRate__c</fullName>
    <label>Daily Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/packaged/main/default/objects/TimeEntry__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Short description of the performed work</description>
    <inlineHelpText>Enter short description of the work performed</inlineHelpText>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

src/packaged/main/default/objects/TimeEntry__c/fields/EndTime__c.field-meta.xml
<CustomField>
    <fullName>EndTime__c</fullName>
    <description>Time when work was finished. Used to calculate duration.</description>
    <inlineHelpText>Time when work was finished.</inlineHelpText>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

src/packaged/main/default/objects/TimeEntry__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Invoice that was manually or automatically created for this Time Entry. If the Invoice is set, the Time Entry is locked from modification.</description>
    <inlineHelpText>Invoice that was created from this Time Entry</inlineHelpText>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>TimeEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/packaged/main/core/objects/TimeEntry__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <description>Time when work started. Will be used to calculate duration</description>
    <inlineHelpText>Time when work started</inlineHelpText>
    <label>Start Time</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

sfdx-source/packaged/main/core/objects/TimeEntry__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/packaged/main/default/classes/TimeEntryTriggerHandler_Test.cls
@isTest
public class TimeEntryTriggerHandler_Test {
    
    @TestSetup
    static void makeData(){
        Account a = TestDataFactory.CreateDefaultAccount();
        insert a;

        Budget__c b = TestDataFactory.CreateBudget(new Budget__c(Account__c = a.Id));
        insert b;

        Invoice__c inv = TestDataFactory.CreateInvoice(new Invoice__c(Account__c = a.Id));
        insert inv;
    }

    @isTest
    static void insert_NewTimeEntry_BudgetSummaryRecalculated() {
        // SETUP
        Budget__c b = [SELECT Id,Account__c FROM Budget__c LIMIT 1];
        TimeEntry__c toInsert = TestDataFactory.CreateTimeEntry(
            new TimeEntry__c(
                Budget__c = b.Id,
                Account__c = b.Account__c,
                DailyRate__c = 1500.00,
                StartTime__c = Time.newInstance(8,0,0,0),
                EndTime__c = Time.newInstance(12,0,0,0),
                Status__c = 'New')
        );

        // ACTION
        Database.SaveResult sr = Database.insert(toInsert, false);

        // VERIFY
        System.assertEquals(true, sr.isSuccess(), sr.getErrors());
        Budget__c newBudget = [SELECT Id,TotalAmountLogged__c,TotalAmountInvoiced__c FROM Budget__c WHERE Id = :b.Id];
        System.assertEquals(750.00, newBudget.TotalAmountLogged__c, 'TotalAmountLogged__c');
        System.assertEquals(0, newBudget.TotalAmountInvoiced__c, 'TotalAmountInvoiced__c');
    }

    @isTest
    static void insert_InvoicedTimeEntry_BudgetSummaryRecalculated() {
        // SETUP
        Budget__c b = [SELECT Id,Account__c FROM Budget__c LIMIT 1];
        Invoice__c invoice = [SELECT Id FROM Invoice__c LIMIT 1];

        TimeEntry__c toInsert = TestDataFactory.CreateTimeEntry(
            new TimeEntry__c(
                Budget__c = b.Id,
                Account__c = b.Account__c,
                Invoice__c = invoice.Id,
                DailyRate__c = 1500.00,
                StartTime__c = Time.newInstance(8,0,0,0),
                EndTime__c = Time.newInstance(12,0,0,0),
                Status__c = 'Approved')
        );

        // ACTION
        Database.SaveResult sr = Database.insert(toInsert, false);

        // VERIFY
        System.assertEquals(true, sr.isSuccess(), sr.getErrors());
        Budget__c newBudget = [SELECT Id,TotalAmountLogged__c,TotalAmountInvoiced__c FROM Budget__c WHERE Id = :b.Id];
        System.assertEquals(750.00, newBudget.TotalAmountLogged__c, 'TotalAmountLogged__c');
        System.assertEquals(750.00, newBudget.TotalAmountInvoiced__c, 'TotalAmountInvoiced__c');
    }

    @isTest
    static void update_ChangeTotalAmount_BudgetSummaryRecalculated() {
        // SETUP
        Budget__c b = [SELECT Id,Account__c FROM Budget__c LIMIT 1];
        Invoice__c invoice = [SELECT Id FROM Invoice__c LIMIT 1];

        TimeEntry__c toUpdate = TestDataFactory.CreateTimeEntry(
            new TimeEntry__c(
                Budget__c = b.Id,
                Account__c = b.Account__c,
                DailyRate__c = 1500.00,
                StartTime__c = Time.newInstance(8,0,0,0),
                EndTime__c = Time.newInstance(12,0,0,0),
                Status__c = 'New')
        );
        insert toUpdate;

        // ACTION
        toUpdate.EndTime__c = Time.newInstance(13,0,0,0);
        toUpdate.DailyRate__c = 1600;
        update toUpdate;

        toUpdate.Invoice__c = invoice.Id;

        Database.SaveResult sr = Database.update(toUpdate, false);

        // VERIFY
        System.assertEquals(true, sr.isSuccess(), sr.getErrors());
        Budget__c newBudget = [SELECT Id,TotalAmountLogged__c,TotalAmountInvoiced__c FROM Budget__c WHERE Id = :b.Id];
        System.assertEquals(1000.00, newBudget.TotalAmountLogged__c, 'TotalAmountLogged__c');
        System.assertEquals(1000.00, newBudget.TotalAmountInvoiced__c, 'TotalAmountInvoiced__c');
    }

    @isTest
    static void update_NoInvoiceRelated_UpdateSucceeds() {
        // SETUP
        Account a = [SELECT Id FROM Account LIMIT 1];
        TimeEntry__c teUnderTest = TestDataFactory.CreateTimeEntry(new TimeEntry__c(Account__c = a.Id));
        insert teUnderTest;

        // ACTION
        teUnderTest.Status__c = 'Approved';
        teUnderTest.StartTime__c = Time.newInstance(8,0,0,0);
        teUnderTest.EndTime__c = Time.newInstance(13,30,0,0);
        Database.SaveResult sr = Database.update(teUnderTest, false);

        // VERIFY
        System.assertEquals(true, sr.isSuccess(), sr.getErrors());
    }

    @isTest
    static void update_AuditableFields_InvoiceRelated_UpdateBlocked() {
        // SETUP
        Account a = [SELECT Id FROM Account LIMIT 1];
        Invoice__c invoice = [SELECT Id FROM Invoice__c LIMIT 1];

        TimeEntry__c teUnderTest = TestDataFactory.CreateTimeEntry(new TimeEntry__c(Account__c = a.Id, Invoice__c = invoice.Id));
        insert teUnderTest;

        // ACTION
        teUnderTest.Status__c = 'Approved';
        teUnderTest.StartTime__c = Time.newInstance(8,0,0,0);
        teUnderTest.EndTime__c = Time.newInstance(13,30,0,0);
        Database.SaveResult sr = Database.update(teUnderTest, false);

        // VERIFY
        System.assertEquals(false, sr.isSuccess(), sr.getErrors());
        System.assertEquals(StatusCode.FIELD_CUSTOM_VALIDATION_EXCEPTION, sr.getErrors()[0].getStatusCode(), 'sr.getErrors()[0].getStatusCode()');
    }

    @isTest
    static void update_NonAuditableFields_InvoiceRelated_UpdateSuccessfull() {
        // SETUP
        Account a = [SELECT Id FROM Account LIMIT 1];
        Invoice__c invoice = [SELECT Id FROM Invoice__c LIMIT 1];

        TimeEntry__c teUnderTest = TestDataFactory.CreateTimeEntry(new TimeEntry__c(Account__c = a.Id, Invoice__c = invoice.Id));
        insert teUnderTest;

        // ACTION
        teUnderTest.Status__c = 'Approved';
        teUnderTest.Description__c = 'Random Text';
        Database.SaveResult sr = Database.update(teUnderTest, false);

        // VERIFY
        System.assertEquals(true, sr.isSuccess(), sr.getErrors());
        //System.assertEquals()
    }

    @isTest
    static void update_InvoiceRelated_RemoveInvoice_UpdateBlocked() {
        // SETUP
        Account a = [SELECT Id FROM Account LIMIT 1];
        Invoice__c invoice = [SELECT Id FROM Invoice__c LIMIT 1];

        TimeEntry__c teUnderTest = TestDataFactory.CreateTimeEntry(new TimeEntry__c(Account__c = a.Id, Invoice__c = invoice.Id));
        insert teUnderTest;

        // ACTION
        teUnderTest.Invoice__c = null;
        Database.SaveResult sr = Database.update(teUnderTest, false);

        // VERIFY
        System.assertEquals(false, sr.isSuccess(), sr.getErrors());
        System.assertEquals(StatusCode.FIELD_CUSTOM_VALIDATION_EXCEPTION, sr.getErrors()[0].getStatusCode(), 'sr.getErrors()[0].getStatusCode()');
        System.assertEquals(Label.Message_TimeEntryValidation_CanNotRemoveInvoice, sr.getErrors()[0].getMessage(), 'sr.getErrors()[0].getMessage()');
    }

    @isTest
    static void update_CancelledInvoiceRelated_RemoveInvoice_UpdateAllowed() {
        // SETUP
        Account a = [SELECT Id FROM Account LIMIT 1];
        Invoice__c invoice = TestDataFactory.CreateInvoice(new Invoice__c(Account__c = a.Id, Status__c = Constants.INVOICE_STATUS_CANCELLED));
        insert invoice;

        TimeEntry__c teUnderTest = TestDataFactory.CreateTimeEntry(new TimeEntry__c(Account__c = a.Id, Invoice__c = invoice.Id));
        insert teUnderTest;

        // ACTION
        teUnderTest.Invoice__c = null;
        Database.SaveResult sr = Database.update(teUnderTest, false);

        // VERIFY
        System.assertEquals(true, sr.isSuccess(), 'isSuccess()' + sr.getErrors());
        TimeEntry__c actualTe = [SELECT Id,Invoice__c FROM TimeEntry__c WHERE Id = : teUnderTest.Id];
        System.assertEquals(null, actualTe.Invoice__c, 'TimeEntry__c.Invoice__c');
    }

    @isTest
    static void delete_ValidTimeEntry_BudgetSummaryRecalculated() {
        // SETUP
        Budget__c b = [SELECT Id,Account__c FROM Budget__c LIMIT 1];
        TimeEntry__c toDelete = TestDataFactory.CreateTimeEntry(
            new TimeEntry__c(
                Budget__c = b.Id,
                Account__c = b.Account__c,
                DailyRate__c = 1500.00,
                StartTime__c = Time.newInstance(8,0,0,0),
                EndTime__c = Time.newInstance(12,0,0,0),
                Status__c = 'New')
        );
        insert toDelete;

        // ACTION
        Database.DeleteResult dr = Database.delete(toDelete, false);

        // VERIFY
        System.assertEquals(true, dr.isSuccess(), dr.getErrors());
        Budget__c newBudget = [SELECT Id,TotalAmountLogged__c,TotalAmountInvoiced__c FROM Budget__c WHERE Id = :b.Id];
        System.assertEquals(0.00, newBudget.TotalAmountLogged__c, 'TotalAmountLogged__c');
        System.assertEquals(0.00, newBudget.TotalAmountInvoiced__c, 'TotalAmountInvoiced__c');
    }

    @isTest
    static void delete_InvoicedTimeEntry_DeleteBlocked() {
        // SETUP
        Account a = [SELECT Id FROM Account LIMIT 1];
        Invoice__c invoice = [SELECT Id FROM Invoice__c LIMIT 1];
        TimeEntry__c teUnderTest = TestDataFactory.CreateTimeEntry(new TimeEntry__c(Account__c = a.Id,Invoice__c = invoice.Id));
        insert teUnderTest;

        // ACTION
        Database.DeleteResult dr = Database.delete(teUnderTest, false);

        // VERIFY
        System.assertEquals(false, dr.isSuccess(), 'DeleteResult.isSuccess()');
        System.assertEquals(StatusCode.FIELD_CUSTOM_VALIDATION_EXCEPTION, dr.getErrors()[0].getStatusCode(), 'dr.getErrors()[0].getStatusCode()');
        System.assertEquals(Label.Message_TimeEntryValidation_CanNotDeleteRecord, dr.getErrors()[0].getMessage(), 'dr.getErrors()[0].getMessage()');
    }

    @isTest
    static void delete_InvoicedTimeEntry_CancelledInvoice_DeleteAllowed() {
        // SETUP
        Account a = [SELECT Id FROM Account LIMIT 1];
        Invoice__c invoice = TestDataFactory.CreateInvoice(new Invoice__c(Account__c = a.Id, Status__c = Constants.INVOICE_STATUS_CANCELLED));

        TimeEntry__c teUnderTest = TestDataFactory.CreateTimeEntry(new TimeEntry__c(Account__c = a.Id,Invoice__c = invoice.Id));
        insert teUnderTest;

        // ACTION
        Database.DeleteResult dr = Database.delete(teUnderTest, false);

        // VERIFY
        System.assertEquals(true, dr.isSuccess(), 'isSuccess(): ' + dr.getErrors());
    }
}