sfdx-source/packaged/main/core/objects/Budget__c/Budget__c.object-meta.xml
<CustomObject>
    <description>Individually controlled budgets for customers (i.e. for projects or specific time periods)</description>
    <label>Budget</label>
    <nameField>
        <label>Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/packaged/main/default/objects/Budget__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The primary account that holds this Budget</description>
    <inlineHelpText>Primary Billing Account</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Budgets</relationshipLabel>
    <relationshipName>Budgets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/packaged/main/core/objects/Budget__c/fields/TotalAmountInvoiced__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountInvoiced__c</fullName>
    <label>Total Ampount Invoiced</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
    <description>Sum of all invoiced time entries (calculated amount) for this Budget</description>
    <inlineHelpText>Sum of amount for all invoiced Time Entries to this Budget</inlineHelpText>
</CustomField>

sfdx-source/packaged/main/core/objects/Budget__c/fields/TotalAmountLogged__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountLogged__c</fullName>
    <label>Total Ampount Logged</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
    <description>Sum of all time entries (calculated amount) for this Budget</description>
    <inlineHelpText>Sum of amount for all Time Entries to this Budget</inlineHelpText>
</CustomField>

sfdx-source/packaged/main/core/classes/BudgetTriggerHandler_Test.cls
@isTest
public class BudgetTriggerHandler_Test {

    @TestSetup
    static void makeData(){
        insert TestDataFactory.CreateDefaultAccount();
    }
    
    /**                             TIME ENTRY STATISTICS                  
    *   - all tests only work on real DB operations, because of caching
    *   - sum for total amount logged
    *   - sum for total amount invoiced
    */

    @isTest
    static void insert_NewBudget_TimeEntrySumsZeroed() {
        // SETUP
        Account a = [SELECT Id FROM Account LIMIT 1];
        Budget__c toInsert = TestDataFactory.CreateBudget(new Budget__c(Account__c = a.Id));
        // ACTION
        Database.SaveResult sr = Database.insert(toInsert, false);
        // VERIFY
        System.assertEquals(true, sr.isSuccess(), sr.getErrors());
        Budget__c actualRecord = [SELECT Id,TotalAmountLogged__c,TotalAmountInvoiced__c FROM Budget__c WHERE Id = :toInsert.Id];
        System.assertEquals(0.0, actualRecord.TotalAmountLogged__c, 'TotalAmountLogged__c');
        System.assertEquals(0.0, actualRecord.TotalAmountInvoiced__c, 'TotalAmountInvoiced__c');
    }

    @isTest
    static void insert_OverrideSumsInNewBudget_TimeEntrySumsCalculated() {
        // SETUP
        Account a = [SELECT Id FROM Account LIMIT 1];
        Budget__c toInsert = TestDataFactory.CreateBudget(new Budget__c(Account__c = a.Id, TotalAmountLogged__c = 100.00, TotalAmountInvoiced__c = 85.23));
        // ACTION
        Database.SaveResult sr = Database.insert(toInsert, false);
        // VERIFY
        System.assertEquals(true, sr.isSuccess(), sr.getErrors());
        Budget__c actualRecord = [SELECT Id,TotalAmountLogged__c,TotalAmountInvoiced__c FROM Budget__c WHERE Id = :toInsert.Id];
        System.assertEquals(0.0, actualRecord.TotalAmountLogged__c, 'TotalAmountLogged__c');
        System.assertEquals(0.0, actualRecord.TotalAmountInvoiced__c, 'TotalAmountInvoiced__c');
    }

    @isTest
    static void update_NoTimeEntries_TimeEntrySumsCalculated() {
        // SETUP
        Account a = [SELECT Id FROM Account LIMIT 1];
        Budget__c toUpdate = TestDataFactory.CreateBudget(new Budget__c(Account__c = a.Id));
        insert toUpdate;

        // ACTION
        toUpdate.TotalAmountLogged__c = 100.00;
        toUpdate.TotalAmountInvoiced__c = 75.00;
        Database.SaveResult sr = Database.update(toUpdate, false);

        // VERIFY
        System.assertEquals(true, sr.isSuccess(), sr.getErrors());
        Budget__c actualRecord = [SELECT Id,TotalAmountLogged__c,TotalAmountInvoiced__c FROM Budget__c WHERE Id = :toUpdate.Id];
        System.assertEquals(0.0, actualRecord.TotalAmountLogged__c, 'TotalAmountLogged__c');
        System.assertEquals(0.0, actualRecord.TotalAmountInvoiced__c, 'TotalAmountInvoiced__c');
    }
}