sfdx-source/packaged/main/core/objects/Budget__c/Budget__c.object-meta.xml
<CustomObject>
    <description>Individually controlled budgets for customers (i.e. for projects or specific time periods)</description>
    <label>Budget</label>
    <nameField>
        <label>Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/packaged/main/trigger-utils/objects/HandlerControl__mdt/HandlerControl__mdt.object-meta.xml
<CustomObject>
    <description>Registers a trigger handler that implements the interface with the framework and allows to control execution.</description>
    <label>Handler Control</label>
    <pluralLabel>Handler Controls</pluralLabel>
</CustomObject>

sfdx-source/packaged/main/trigger-utils/objects/HandlerControl__mdt/fields/Handler__c.field-meta.xml
<CustomField>
    <fullName>Handler__c</fullName>
    <description>The exact class name of the handler that implements the interface. This is used to dynamically construct the class during runtime.</description>
    <inlineHelpText>The developer name of the Apex Class that implements the interface</inlineHelpText>
    <label>Handler</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

src/packaged/main/trigger-utils/objects/HandlerControl__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Activates the handler to be processed during execution of triggers.</description>
    <inlineHelpText>Activates the handler for processing</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/packaged/main/trigger-utils/objects/HandlerControl__mdt/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The order of execution for this specific handler. Higher numbers are executed earlier in a transaction.</description>
    <inlineHelpText>Higher priorities are executed earlier during a transaction.</inlineHelpText>
    <label>Priority</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdx-source/packaged/main/trigger-utils/objects/HandlerControl__mdt/fields/SObject__c.field-meta.xml
<CustomField>
    <fullName>SObject__c</fullName>
    <description>The SObject for which the configuration will be executed.</description>
    <inlineHelpText>Select the SObject-Type where this configuration will be triggered</inlineHelpText>
    <label>SObject</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Triggers</relationshipLabel>
    <relationshipName>Triggers</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

sfdx-source/packaged/main/core/objects/TimeEntry__c/TimeEntry__c.object-meta.xml
<CustomObject>
    <description>An individual time entry as unit of work that can be invoiced.</description>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>{YYYYMMDD}-{000000}</displayFormat>
        <label>Time Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/packaged/main/core/objects/TimeEntry__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Add this time entry to a budget to roll up costs</description>
    <label>Budget</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Budget must be related to the same Account</errorMessage>
        <filterItems>
            <field>Budget__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <infoMessage>Select a Budget from the same Account</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Budget__c</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>TimeEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/packaged/main/trigger-utils/classes/T_Dispatcher.cls
@isTest
public class T_Dispatcher {
    
    /**************************************************************************************
    *                                       DISPATCHER
    *   The tests don't test functionality but provide code coverage and verify that any configurations
    *   registered for the framework (by dependend packages) do not break standard functionality
    *   Actual testing of functionality is expected by the implementing package that registers the handler
    /**************************************************************************************/

    @isTest
    static void init_NoScope_NoActiveHandlers() {
        // SETUP
        Dispatcher d = new Dispatcher();
        // VERIFY
        System.assertEquals(0, d.activeHandlers.size(), 'activeHandlers.size()');
    }

    @isTest
    static void initHandlers_ValidConfig_HandlerInitialized() {
        // SETUP
        HandlerControl__mdt testConfig = new HandlerControl__mdt(SObject__c = 'Account',
                                                                 DeveloperName = 'TEST_HANDLER_CONFIG',
                                                                 IsActive__c = true,
                                                                 Priority__c = 0,
                                                                 Handler__c = 'T_Dispatcher.TestTriggerHandler');
        // ACTION
        List<ITriggerHandler> handlers = new Dispatcher().initHandlers(new List<HandlerControl__mdt>{testConfig});
        // VERIFY
        System.assertEquals(1, handlers.size(), 'handlers.size()');
    }

    @isTest
    static void initHandlers_InvalidConfig_NoHandlerInitialized() {
        // SETUP
        HandlerControl__mdt testConfig = new HandlerControl__mdt(SObject__c = 'Account',
                                                                 DeveloperName = 'TEST_HANDLER_CONFIG',
                                                                 IsActive__c = true,
                                                                 Priority__c = 0,
                                                                 Handler__c = 'T_Dispatcher.InvalidHandlerName');
        // ACTION
        List<ITriggerHandler> handlers = new Dispatcher().initHandlers(new List<HandlerControl__mdt>{testConfig});
        // VERIFY
        System.assertEquals(0, handlers.size(), 'handlers.size()');
    }

    @isTest
    static void executeHandlers_Account_AllHandlersExecuted() {
        // SETUP
        Dispatcher sObjDispatcher = new Dispatcher(Account.getSObjectType());
        // ACTION
        sObjDispatcher.executeHandlers();
        // VERIFY
        System.assertEquals(
            [SELECT COUNT() FROM HandlerControl__mdt WHERE SObject__r.QualifiedApiName = 'Account' AND IsActive__c = true], 
            sObjDispatcher.activeHandlers.size(), 
            'activeHandlers.size()'
        );
    }

    @isTest
    static void executeHandlers_TimeEntry_AllHandlersExecuted(){
        // SETUP
        Dispatcher sObjDispatcher = new Dispatcher(TimeEntry__c.getSObjectType());
        // ACTION
        sObjDispatcher.executeHandlers();
        // VERIFY
        System.assertEquals(
            [SELECT COUNT() FROM HandlerControl__mdt WHERE SObject__r.QualifiedApiName = 'TimeEntry__c' AND IsActive__c = true], 
            sObjDispatcher.activeHandlers.size(), 
            'activeHandlers.size()'
        );    
    }

    @isTest
    static void executeHandlers_Budget_AllHandlersExecuted(){
        // SETUP
        Dispatcher sObjDispatcher = new Dispatcher(Budget__c.getSObjectType());
        // ACTION
        sObjDispatcher.executeHandlers();
        // VERIFY
        System.assertEquals(
            [SELECT COUNT() FROM HandlerControl__mdt WHERE SObject__r.QualifiedApiName = 'Budget__c' AND IsActive__c = true], 
            sObjDispatcher.activeHandlers.size(), 
            'activeHandlers.size()'
        );    
    }

    public class TestTriggerHandler implements ITriggerHandler {
        public void execute() { }
    }
}