sfdx-source/packaged/main/core/objects/Budget__c/Budget__c.object-meta.xml
<CustomObject>
    <description>Individually controlled budgets for customers (i.e. for projects or specific time periods)</description>
    <label>Budget</label>
    <nameField>
        <label>Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/packaged/main/core/objects/TimeEntry__c/TimeEntry__c.object-meta.xml
<CustomObject>
    <description>An individual time entry as unit of work that can be invoiced.</description>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>{YYYYMMDD}-{000000}</displayFormat>
        <label>Time Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/packaged/main/core/objects/TimeEntry__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Add this time entry to a budget to roll up costs</description>
    <label>Budget</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Budget must be related to the same Account</errorMessage>
        <filterItems>
            <field>Budget__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <infoMessage>Select a Budget from the same Account</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Budget__c</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>TimeEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/packaged/main/core/objects/TimeEntry__c/fields/IsInvoiced__c.field-meta.xml
<CustomField>
    <fullName>IsInvoiced__c</fullName>
    <formula>NOT(ISBLANK(Invoice__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Invoiced</label>
    <type>Checkbox</type>
    <description>Calculates the Invoicing Status for easy SOQL from Invoice Lookup</description>
</CustomField>

sfdx-source/packaged/main/core/classes/TimeEntryTriggerHandler.cls
public without sharing class TimeEntryTriggerHandler implements ITriggerHandler {

    private Map<Id, Budget__c> relatedBudgets;

    public TimeEntryTriggerHandler() {
        // finding all budgets that are affected by this operation
        Set<Id> budgetIds = new Set<Id>();
        if (Trigger.new != null) budgetIds.addAll(ListUtils.extractIdsFromSObjectList(Trigger.new, TimeEntry__c.Budget__c));
        if (Trigger.old != null) budgetIds.addAll(ListUtils.extractIdsFromSObjectList(Trigger.old, TimeEntry__c.Budget__c));
        relatedBudgets = new Map<Id, Budget__c>([SELECT Id FROM Budget__c WHERE Id IN :budgetIds]);

    }

    /** @Description
    *   Execute implements the ITriggerHandler interface and is called once per execution context
    *   (before & after each). The implementation is responsible for dispatching the individual trigger
    *   scopes (insert, update, delete, etc) and setting order of execution for the functional blocks.
    */
    public void execute() {
        if (!Trigger.isExecuting) return;
        switch on Trigger.OperationType {
            when AFTER_INSERT { recalculateRelatedBudgets(); }
            when AFTER_UPDATE { recalculateRelatedBudgets(); }
            when AFTER_UNDELETE { recalculateRelatedBudgets(); }
            when BEFORE_DELETE { for (SObject so : Trigger.old) beforeDelete((TimeEntry__c)so); }
            when AFTER_DELETE { recalculateRelatedBudgets(); }
        }
    }

    private void recalculateRelatedBudgets() {
        update relatedBudgets.values();
    }

    private void beforeDelete(TimeEntry__c so) {
        if (so.IsInvoiced__c) so.addError(Label.ValidationError_CanNotDeleteInvoicedTimeEntry);
    }

}