sfdx-source/packaged/main/core/objects/Budget__c/Budget__c.object-meta.xml
<CustomObject>
    <description>Individually controlled budgets for customers (i.e. for projects or specific time periods)</description>
    <label>Budget</label>
    <nameField>
        <label>Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/packaged/main/core/objects/Budget__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/packaged/main/default/objects/Budget__c/fields/TotalAmountInvoiced__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountInvoiced__c</fullName>
    <label>Total Amount Invoiced</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
    <description>Sum of all invoiced time entries (calculated amount) for this Budget</description>
    <inlineHelpText>Sum of amount for all invoiced Time Entries to this Budget</inlineHelpText>
</CustomField>

src/packaged/main/default/objects/Budget__c/fields/TotalAmountLogged__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountLogged__c</fullName>
    <label>Total Amount Logged</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
    <description>Sum of all time entries (calculated amount) for this Budget</description>
    <inlineHelpText>Sum of amount for all Time Entries to this Budget</inlineHelpText>
</CustomField>

sfdx-source/packaged/main/core/objects/TimeEntry__c/TimeEntry__c.object-meta.xml
<CustomObject>
    <description>An individual time entry as unit of work that can be invoiced.</description>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>{YYYYMMDD}-{000000}</displayFormat>
        <label>Time Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/packaged/main/core/objects/TimeEntry__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Add this time entry to a budget to roll up costs</description>
    <label>Budget</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Budget must be related to the same Account</errorMessage>
        <filterItems>
            <field>Budget__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <infoMessage>Select a Budget from the same Account</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Budget__c</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>TimeEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/packaged/main/core/objects/TimeEntry__c/fields/DailyRate__c.field-meta.xml
<CustomField>
    <fullName>DailyRate__c</fullName>
    <label>Daily Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

sfdx-source/packaged/main/core/objects/TimeEntry__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>The calender date where this time entry / work occured</description>
    <inlineHelpText>Calender date where work was done</inlineHelpText>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

sfdx-source/packaged/main/core/objects/TimeEntry__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>Calculated duration in decimal hour format (3 hours 30 minutes = 3,5)</description>
    <formula>(HOUR(EndTime__c) - HOUR(StartTime__c)) + (MINUTE(EndTime__c)-MINUTE(StartTime__c)) / 60</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Calculated duration</inlineHelpText>
    <label>Duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

src/packaged/main/default/objects/TimeEntry__c/fields/IsInvoiced__c.field-meta.xml
<CustomField>
    <fullName>IsInvoiced__c</fullName>
    <description>A Time Entry is invoiced, if it is related to a non cancelled invoice record (Draft or Activated). Being invoiced blocks the Time Entry from being edited.</description>
    <formula>NOT(ISBLANK(Invoice__c)) &amp;&amp; NOT(ISPICKVAL(Invoice__r.Status__c, &#39;Cancelled&#39;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Invoiced</label>
    <type>Checkbox</type>
</CustomField>

sfdx-source/packaged/main/core/objects/TimeEntry__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/packaged/main/default/objects/TimeEntry__c/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <formula>DailyRate__c * (Duration__c / 8)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/packaged/main/default/classes/BudgetTriggerHandler.cls
public without sharing class BudgetTriggerHandler implements ITriggerHandler {

    /** @Description    Organizes the lists of Time Entries by Budget id */
    private Map<Id, List<TimeEntry__c>> budgetTimeEntries = new Map<Id, List<TimeEntry__c>>();

    public BudgetTriggerHandler() {
        // load time entries in update and undelete context only
        if (Trigger.isExecuting && (Trigger.isUpdate || Trigger.isUndelete)) {
            for (Budget__c b : [SELECT Id, (SELECT Id,DailyRate__c,Date__c,Status__c,TotalAmount__c,Duration__c,IsInvoiced__c FROM TimeEntries__r) 
                                FROM Budget__c WHERE Id IN :Trigger.newMap.keySet()]) {
                budgetTimeEntries.put(b.Id, b.TimeEntries__r);
            }
        }
    }

    /** @Description
    *   Implementation of ITriggerHandler interface. Entry point to execute all trigger logic.
    *   This method solves trigger context and bulkification and dispatches to more specific functions
    *   to implement the individually needed logic.
    */
    public void execute() {
        if (!Trigger.isExecuting) return;
        switch on Trigger.OperationType {
            when BEFORE_INSERT { for (SObject so : Trigger.new) beforeInsert((Budget__c)so); }
            when BEFORE_UPDATE { for (SObject so : Trigger.old) beforeUpdate((Budget__c)so, (Budget__c)Trigger.newMap.get(so.Id)); }
            when AFTER_UNDELETE {
                List<Budget__c> budgetsToUndelete = [SELECT Id FROM Budget__c WHERE Id IN :Trigger.newMap.keySet() FOR UPDATE];
                for (Budget__c b : budgetsToUndelete) afterUndelete(b);
                update budgetsToUndelete;
            }
        }
    }

    public void beforeUpdate(Budget__c oldSo, Budget__c newSo) {
        updateTotalAmountInvoiced(newSo);
        updateTotalAmountLogged(newSo);
    }

    public void beforeInsert(Budget__c newSo) {
        newSo.TotalAmountInvoiced__c = 0;
        newSo.TotalAmountLogged__c = 0;
    }

    public void afterUndelete(Budget__c newSo) {
        updateTotalAmountInvoiced(newSo);
        updateTotalAmountLogged(newSo);
    }

    private void updateTotalAmountLogged(Budget__c newSo) {
        newSo.TotalAmountLogged__c = ListUtils.summarizeSObjectListField(
            budgetTimeEntries.get(newSo.Id), 
            TimeEntry__c.TotalAmount__c,
            ListUtils.SummarizeOperation.SUM
        );
    }

    private void updateTotalAmountInvoiced(Budget__c newSo) {
        List<TimeEntry__c> invoicedTimeEntries = new List<TimeEntry__c>();
        for (TimeEntry__c te : budgetTimeEntries.get(newSo.Id)) {
            if (te.IsInvoiced__c) invoicedTimeEntries.add(te);
        }

        newSo.TotalAmountInvoiced__c = ListUtils.summarizeSObjectListField(
            invoicedTimeEntries,
            TimeEntry__c.TotalAmount__c,
            ListUtils.SummarizeOperation.SUM
        );      
    }
}