sfdx-source/packaged/main/core/objects/Budget__c/Budget__c.object-meta.xml
<CustomObject>
    <description>Individually controlled budgets for customers (i.e. for projects or specific time periods)</description>
    <label>Budget</label>
    <nameField>
        <label>Budget Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Budgets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/packaged/main/default/objects/Budget__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The primary account that holds this Budget</description>
    <inlineHelpText>Primary Billing Account</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Budgets</relationshipLabel>
    <relationshipName>Budgets</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/packaged/main/core/objects/Budget__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/packaged/main/default/objects/Budget__c/fields/TotalAmountInvoiced__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountInvoiced__c</fullName>
    <label>Total Amount Invoiced</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
    <description>Sum of all invoiced time entries (calculated amount) for this Budget</description>
    <inlineHelpText>Sum of amount for all invoiced Time Entries to this Budget</inlineHelpText>
</CustomField>

src/packaged/main/default/objects/Budget__c/fields/TotalAmountLogged__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountLogged__c</fullName>
    <label>Total Amount Logged</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
    <description>Sum of all time entries (calculated amount) for this Budget</description>
    <inlineHelpText>Sum of amount for all Time Entries to this Budget</inlineHelpText>
</CustomField>

sfdx-source/packaged/main/core/objects/TimeEntry__c/TimeEntry__c.object-meta.xml
<CustomObject>
    <description>An individual time entry as unit of work that can be invoiced.</description>
    <label>Time Entry</label>
    <nameField>
        <displayFormat>{YYYYMMDD}-{000000}</displayFormat>
        <label>Time Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/packaged/main/core/objects/TimeEntry__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The primary account where this Time Entry will be billed to</description>
    <inlineHelpText>Primary Billing Account</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>TimeEntries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

sfdx-source/packaged/main/core/objects/TimeEntry__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Add this time entry to a budget to roll up costs</description>
    <label>Budget</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The Budget must be related to the same Account</errorMessage>
        <filterItems>
            <field>Budget__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <infoMessage>Select a Budget from the same Account</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Budget__c</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>TimeEntries</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/packaged/main/core/objects/TimeEntry__c/fields/DailyRate__c.field-meta.xml
<CustomField>
    <fullName>DailyRate__c</fullName>
    <label>Daily Rate</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

src/packaged/main/default/objects/TimeEntry__c/fields/EndTime__c.field-meta.xml
<CustomField>
    <fullName>EndTime__c</fullName>
    <description>Time when work was finished. Used to calculate duration.</description>
    <inlineHelpText>Time when work was finished.</inlineHelpText>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

sfdx-source/packaged/main/core/objects/TimeEntry__c/fields/StartTime__c.field-meta.xml
<CustomField>
    <fullName>StartTime__c</fullName>
    <description>Time when work started. Will be used to calculate duration</description>
    <inlineHelpText>Time when work started</inlineHelpText>
    <label>Start Time</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

sfdx-source/packaged/main/core/objects/TimeEntry__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/packaged/main/default/classes/BudgetTriggerHandler_Test.cls
@isTest
public class BudgetTriggerHandler_Test {

    @TestSetup
    static void makeData(){
        insert TestDataFactory.CreateDefaultAccount();
    }
    
    /**                             TIME ENTRY STATISTICS                  
    *   - all tests only work on real DB operations, because of caching
    *   - sum for total amount logged
    *   - sum for total amount invoiced
    */

    @isTest
    static void insert_NewBudget_TimeEntrySumsZeroed() {
        // SETUP
        Account a = [SELECT Id FROM Account LIMIT 1];
        Budget__c toInsert = TestDataFactory.CreateBudget(new Budget__c(Account__c = a.Id));
        // ACTION
        Database.SaveResult sr = Database.insert(toInsert, false);
        // VERIFY
        System.assertEquals(true, sr.isSuccess(), sr.getErrors());
        Budget__c actualRecord = [SELECT Id,TotalAmountLogged__c,TotalAmountInvoiced__c FROM Budget__c WHERE Id = :toInsert.Id];
        System.assertEquals(0.0, actualRecord.TotalAmountLogged__c, 'TotalAmountLogged__c');
        System.assertEquals(0.0, actualRecord.TotalAmountInvoiced__c, 'TotalAmountInvoiced__c');
    }

    @isTest
    static void insert_OverrideSumsInNewBudget_TimeEntrySumsCalculated() {
        // SETUP
        Account a = [SELECT Id FROM Account LIMIT 1];
        Budget__c toInsert = TestDataFactory.CreateBudget(new Budget__c(Account__c = a.Id, TotalAmountLogged__c = 100.00, TotalAmountInvoiced__c = 85.23));
        // ACTION
        Database.SaveResult sr = Database.insert(toInsert, false);
        // VERIFY
        System.assertEquals(true, sr.isSuccess(), sr.getErrors());
        Budget__c actualRecord = [SELECT Id,TotalAmountLogged__c,TotalAmountInvoiced__c FROM Budget__c WHERE Id = :toInsert.Id];
        System.assertEquals(0.0, actualRecord.TotalAmountLogged__c, 'TotalAmountLogged__c');
        System.assertEquals(0.0, actualRecord.TotalAmountInvoiced__c, 'TotalAmountInvoiced__c');
    }

    @isTest
    static void update_NoTimeEntries_TimeEntrySumsCalculated() {
        // SETUP
        Account a = [SELECT Id FROM Account LIMIT 1];
        Budget__c toUpdate = TestDataFactory.CreateBudget(new Budget__c(Account__c = a.Id));
        insert toUpdate;

        // ACTION
        toUpdate.TotalAmountLogged__c = 100.00;
        toUpdate.TotalAmountInvoiced__c = 75.00;
        Database.SaveResult sr = Database.update(toUpdate, false);

        // VERIFY
        System.assertEquals(true, sr.isSuccess(), sr.getErrors());
        Budget__c actualRecord = [SELECT Id,TotalAmountLogged__c,TotalAmountInvoiced__c FROM Budget__c WHERE Id = :toUpdate.Id];
        System.assertEquals(0.0, actualRecord.TotalAmountLogged__c, 'TotalAmountLogged__c');
        System.assertEquals(0.0, actualRecord.TotalAmountInvoiced__c, 'TotalAmountInvoiced__c');
    }

    @isTest
    static void undelete_HadTimeEntriesBeforeDelete_TimeEntrySumsCalculated() {
        // SETUP
        Account a = [SELECT Id FROM Account LIMIT 1];
        Budget__c toUndelete = TestDataFactory.CreateBudget(new Budget__c(Account__c = a.Id));
        insert toUndelete;

        TimeEntry__c te = TestDataFactory.CreateTimeEntry(
            new TimeEntry__c(
                Budget__c = toUndelete.Id,
                Account__c = a.Id,
                DailyRate__c = 1500.00,
                StartTime__c = Time.newInstance(8,0,0,0),
                EndTime__c = Time.newInstance(12,0,0,0),
                Status__c = 'Approved')
        );
        insert te;

        // ACTION
        Id undeleteId = toUndelete.Id;
        Database.DeleteResult dr = Database.delete(undeleteId);

        // update time entry, so budget will need recalculation after undelete
        te = [SELECT Id FROM TimeEntry__c WHERE Id = :te.Id];
        te.DailyRate__c = 1600.00;
        update te;
        
        // undelete budget, which will also restore lookup
        Database.UndeleteResult ur = Database.undelete(undeleteId, false);

        // VERIFY
        System.assertEquals(true, dr.isSuccess(), 'DeleteResult: ' + dr.getErrors());
        System.assertEquals(true, ur.isSuccess(), 'UndeleteResult: ' + ur.getErrors());
        Budget__c actualRecord = [SELECT Id,TotalAmountLogged__c,TotalAmountInvoiced__c,(SELECT Id FROM TimeEntries__r) FROM Budget__c WHERE Id = :toUndelete.Id];
        System.assertEquals(1, actualRecord.TimeEntries__r.size(), 'TimeEntries__r.size()');
        System.assertEquals(800.0, actualRecord.TotalAmountLogged__c, 'TotalAmountLogged__c');
        System.assertEquals(0.0, actualRecord.TotalAmountInvoiced__c, 'TotalAmountInvoiced__c');
    }
}